In [38]:
# Install ipython-sql if not already installed
# !pip install ipython-sql

In [2]:
import sqlite3
import sql
import pandas as pd
import numpy as np

# Connect to a database (creates the database file if it doesn't exist)
cnn = sqlite3.connect('northwind1.db')

In [3]:
import sql

# Load the SQL extension
%load_ext sql

# Connect to a SQLite database
%sql sqlite:///northwind1.db

#display style of SQL query results in Jupyter Notebook
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [4]:
%%sql

SELECT name FROM sqlite_master WHERE type='table';

 * sqlite:///northwind1.db
Done.

[('sqlite_sequence',),
 ('CustomerCustomerDemo',),
 ('CustomerDemographics',),
 ('EmployeeTerritories',),
 ('Regions',),
 ('Territories',),
 ('Categories',),
 ('Orders',),
 ('Products',),
 ('Shippers',),
 ('Suppliers',),
 ('Employees',),
 ('Customers_new',),
 ('Customers',)]

In [11]:
from sqlalchemy import create_engine
import pandas as pd

# Connect to the SQLite database
engine = create_engine("sqlite:///northwind1.db")

# List of all tables
tables = [
     "EmployeeTerritories", "Regions", "Territories",
    "Categories", "Orders", "Products", "Shippers", "Suppliers", "Employees", "Customers"
]

# Loop through each table and display top 2 rows
for table in tables:
    print(f"\n--- {table} ---")
    df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 5;", engine)
    display(df)  # use display() in Jupyter to format nicely

--- EmployeeTerritories ---

   EmployeeID TerritoryID
0           1       06897
1           1       19713
2           2       01581
3           2       01730
4           2       01833

--- Regions ---

   RegionID RegionDescription
0         1           Eastern
1         2           Western
2         3          Northern
3         4          Southern

--- Territories ---

  TerritoryID TerritoryDescription  RegionID
0       01581             Westboro         1
1       01730              Bedford         1
2       01833            Georgetow         1
3       02116               Boston         1
4       02139            Cambridge         1

--- Categories ---

,CategoryID,CategoryName,Description
0,1,Beverages,"Soft drinks, coffees, teas, beers, and ales"
1,2,Condiments,"Sweet and savory sauces, relishes, spreads, an..."
2,3,Confections,"Desserts, candies, and sweet breads"
3,4,Dairy Products,Cheeses
4,5,Grains/Cereals,"Breads, crackers, pasta, and cereal"

--- Orders ---

   OrderID CustomerID  EmployeeID   OrderDate  ShipperID
0    10248      VINET           5  2016-07-04          3
1    10249      TOMSP           6  2016-07-05          1
2    10250      HANAR           4  2016-07-08          2
3    10251      VICTE           3  2016-07-08          1
4    10252      SUPRD           4  2016-07-09          2

--- Products ---

,ProductID,ProductName,SupplierID,CategoryID,Unit,Price
0,1,Chai,1,1,10 boxes x 20 bags,18.00
1,2,Chang,1,1,24 - 12 oz bottles,19.00
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

--- Shippers ---

   ShipperID       ShipperName           Phone
0          1    Speedy Express  (503) 555-9831
1          2    United Package  (503) 555-3199
2          3  Federal Shipping  (503) 555-9931

--- Suppliers ---

,SupplierID,SupplierName,ContactName,Address,City,PostalCode,Country,Phone
0,1,Exotic Liquids,Charlotte Cooper,49 Gilbert St.,London,EC1 4SD,UK,(171) 555-2222
1,2,New Orleans Cajun Delights,Shelley Burke,P.O. Box 78934,New Orleans,70117,USA,(100) 555-4822
2,3,Grandma Kelly's Homestead,Regina Murphy,707 Oxford Rd.,Ann Arbor,48104,USA,(313) 555-5735
3,4,Tokyo Traders,Yoshi Nagase,9-8 Sekimai\nMusashino-shi,Tokyo,100,Japan,(03) 3555-5011
4,5,Cooperativa de Quesos 'Las Cabras',Antonio del Valle Saavedra,Calle del Rosal 4,Oviedo,33007,Spain,(98) 598 76 54

--- Employees ---

,EmployeeID,LastName,FirstName,BirthDate,Notes
0,1,Davolio,Nancy,1968-12-08,Education includes a BA in psychology from Col...
1,2,Fuller,Andrew,1972-02-19,Andrew received his BTS commercial in 1974 and...
2,3,Leverling,Janet,1983-08-30,Janet has a BS degree in chemistry from Boston...
3,4,Peacock,Margaret,1957-09-19,Margaret holds a BA in English literature from...
4,5,Buchanan,Steven,1975-03-04,Steven Buchanan graduated from St. Andrews Uni...

--- Customers ---

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
0,1,Alfreds Futterkiste,Maria Anders,Obere Str. 57,Berlin,12209,Germany
1,2,Ana Trujillo Emparedados y helados,Ana Trujillo,Avda. de la Constitución 2222,México D.F.,05021,Mexico
2,3,Antonio Moreno Taquería,Antonio Moreno,Mataderos 2312,México D.F.,05023,Mexico
3,4,Around the Horn,Thomas Hardy,120 Hanover Sq.,London,WA1 1DP,UK
4,5,Berglunds snabbköp,Christina Berglund,Berguvsvägen 8,Luleå,S-958 22,Sweden

In [12]:
%%sql

SELECT * 
FROM Products
Limit 5;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 1, '10 boxes x 20 bags', 18),
 (2, 'Chang', 1, 1, '24 - 12 oz bottles', 19),
 (3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10),
 (4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22),
 (5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35)]

# 1️⃣ SUM() — Total Price Across All Rows

In [13]:
%%sql
SELECT 
    ProductID,
    ProductName,
    Price,
    SUM(Price) OVER () AS total_price_all_products
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 18, 2222.71),
 (2, 'Chang', 19, 2222.71),
 (3, 'Aniseed Syrup', 10, 2222.71),
 (4, "Chef Anton's Cajun Seasoning", 22, 2222.71),
 (5, "Chef Anton's Gumbo Mix", 21.35, 2222.71),
 (6, "Grandma's Boysenberry Spread", 25, 2222.71),
 (7, "Uncle Bob's Organic Dried Pears", 30, 2222.71),
 (8, 'Northwoods Cranberry Sauce', 40, 2222.71),
 (9, 'Mishi Kobe Niku', 97, 2222.71),
 (10, 'Ikura', 31, 2222.71),
 (11, 'Queso Cabrales', 21, 2222.71),
 (12, 'Queso Manchego La Pastora', 38, 2222.71),
 (13, 'Konbu', 6, 2222.71),
 (14, 'Tofu', 23.25, 2222.71),
 (15, 'Genen Shouyu', 15.5, 2222.71),
 (16, 'Pavlova', 17.45, 2222.71),
 (17, 'Alice Mutton', 39, 2222.71),
 (18, 'Carnarvon Tigers', 62.5, 2222.71),
 (19, 'Teatime Chocolate Biscuits', 9.2, 2222.71),
 (20, "Sir Rodney's Marmalade", 81, 2222.71),
 (21, "Sir Rodney's Scones", 10, 2222.71),
 (22, "Gustaf's Knäckebröd", 21, 2222.71),
 (23, 'Tunnbröd', 9, 2222.71),
 (24, 'Guaraná Fantástica', 4.5, 2222.71),
 (25, 'NuNuCa Nuß-Nougat-Creme', 14, 2222.71),
 (26, 'Gumbär Gummibärchen', 31.23, 2222.71),
 (27, 'Schoggi Schokolade', 43.9, 2222.71),
 (28, 'Rössle Sauerkraut', 45.6, 2222.71),
 (29, 'Thüringer Rostbratwurst', 123.79, 2222.71),
 (30, 'Nord-Ost Matjeshering', 25.89, 2222.71),
 (31, 'Gorgonzola Telino', 12.5, 2222.71),
 (32, 'Mascarpone Fabioli', 32, 2222.71),
 (33, 'Geitost', 2.5, 2222.71),
 (34, 'Sasquatch Ale', 14, 2222.71),
 (35, 'Steeleye Stout', 18, 2222.71),
 (36, 'Inlagd Sill', 19, 2222.71),
 (37, 'Gravad lax', 26, 2222.71),
 (38, 'Côte de Blaye', 263.5, 2222.71),
 (39, 'Chartreuse verte', 18, 2222.71),
 (40, 'Boston Crab Meat', 18.4, 2222.71),
 (41, "Jack's New England Clam Chowder", 9.65, 2222.71),
 (42, 'Singaporean Hokkien Fried Mee', 14, 2222.71),
 (43, 'Ipoh Coffee', 46, 2222.71),
 (44, 'Gula Malacca', 19.45, 2222.71),
 (45, 'Rogede sild', 9.5, 2222.71),
 (46, 'Spegesild', 12, 2222.71),
 (47, 'Zaanse koeken', 9.5, 2222.71),
 (48, 'Chocolade', 12.75, 2222.71),
 (49, 'Maxilaku', 20, 2222.71),
 (50, 'Valkoinen suklaa', 16.25, 2222.71),
 (51, 'Manjimup Dried Apples', 53, 2222.71),
 (52, 'Filo Mix', 7, 2222.71),
 (53, 'Perth Pasties', 32.8, 2222.71),
 (54, 'Tourtière', 7.45, 2222.71),
 (55, 'Pâté chinois', 24, 2222.71),
 (56, 'Gnocchi di nonna Alice', 38, 2222.71),
 (57, 'Ravioli Angelo', 19.5, 2222.71),
 (58, 'Escargots de Bourgogne', 13.25, 2222.71),
 (59, 'Raclette Courdavault', 55, 2222.71),
 (60, 'Camembert Pierrot', 34, 2222.71),
 (61, "Sirop d'érable", 28.5, 2222.71),
 (62, 'Tarte au sucre', 49.3, 2222.71),
 (63, 'Vegie-spread', 43.9, 2222.71),
 (64, 'Wimmers gute Semmelknödel', 33.25, 2222.71),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 21.05, 2222.71),
 (66, 'Louisiana Hot Spiced Okra', 17, 2222.71),
 (67, 'Laughing Lumberjack Lager', 14, 2222.71),
 (68, 'Scottish Longbreads', 12.5, 2222.71),
 (69, 'Gudbrandsdalsost', 36, 2222.71),
 (70, 'Outback Lager', 15, 2222.71),
 (71, 'Flotemysost', 21.5, 2222.71),
 (72, 'Mozzarella di Giovanni', 34.8, 2222.71),
 (73, 'Röd Kaviar', 15, 2222.71),
 (74, 'Longlife Tofu', 10, 2222.71),
 (75, 'Rhönbräu Klosterbier', 7.75, 2222.71),
 (76, 'Lakkalikööri', 18, 2222.71),
 (77, 'Original Frankfurter grüne Soße', 13, 2222.71)]

In [24]:
%%sql
SELECT 
    SUM(Price) AS total_price_all_products
FROM Products;

 * sqlite:///northwind1.db
Done.

[(2222.71,)]

# 2️⃣ SUM() — Partition by Category

In [14]:
%%sql
SELECT 
    ProductID,
    ProductName,
    CategoryID,
    Price,
    SUM(Price) OVER (PARTITION BY CategoryID) AS category_total_price
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 18, 455.75),
 (2, 'Chang', 1, 19, 455.75),
 (24, 'Guaraná Fantástica', 1, 4.5, 455.75),
 (34, 'Sasquatch Ale', 1, 14, 455.75),
 (35, 'Steeleye Stout', 1, 18, 455.75),
 (38, 'Côte de Blaye', 1, 263.5, 455.75),
 (39, 'Chartreuse verte', 1, 18, 455.75),
 (43, 'Ipoh Coffee', 1, 46, 455.75),
 (67, 'Laughing Lumberjack Lager', 1, 14, 455.75),
 (70, 'Outback Lager', 1, 15, 455.75),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 455.75),
 (76, 'Lakkalikööri', 1, 18, 455.75),
 (3, 'Aniseed Syrup', 2, 10, 276.75),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 276.75),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 276.75),
 (6, "Grandma's Boysenberry Spread", 2, 25, 276.75),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 276.75),
 (15, 'Genen Shouyu', 2, 15.5, 276.75),
 (44, 'Gula Malacca', 2, 19.45, 276.75),
 (61, "Sirop d'érable", 2, 28.5, 276.75),
 (63, 'Vegie-spread', 2, 43.9, 276.75),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 276.75),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 276.75),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 276.75),
 (16, 'Pavlova', 3, 17.45, 327.08),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 327.08),
 (20, "Sir Rodney's Marmalade", 3, 81, 327.08),
 (21, "Sir Rodney's Scones", 3, 10, 327.08),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 327.08),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 327.08),
 (27, 'Schoggi Schokolade', 3, 43.9, 327.08),
 (47, 'Zaanse koeken', 3, 9.5, 327.08),
 (48, 'Chocolade', 3, 12.75, 327.08),
 (49, 'Maxilaku', 3, 20, 327.08),
 (50, 'Valkoinen suklaa', 3, 16.25, 327.08),
 (62, 'Tarte au sucre', 3, 49.3, 327.08),
 (68, 'Scottish Longbreads', 3, 12.5, 327.08),
 (11, 'Queso Cabrales', 4, 21, 287.3),
 (12, 'Queso Manchego La Pastora', 4, 38, 287.3),
 (31, 'Gorgonzola Telino', 4, 12.5, 287.3),
 (32, 'Mascarpone Fabioli', 4, 32, 287.3),
 (33, 'Geitost', 4, 2.5, 287.3),
 (59, 'Raclette Courdavault', 4, 55, 287.3),
 (60, 'Camembert Pierrot', 4, 34, 287.3),
 (69, 'Gudbrandsdalsost', 4, 36, 287.3),
 (71, 'Flotemysost', 4, 21.5, 287.3),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 287.3),
 (22, "Gustaf's Knäckebröd", 5, 21, 141.75),
 (23, 'Tunnbröd', 5, 9, 141.75),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 141.75),
 (52, 'Filo Mix', 5, 7, 141.75),
 (56, 'Gnocchi di nonna Alice', 5, 38, 141.75),
 (57, 'Ravioli Angelo', 5, 19.5, 141.75),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 141.75),
 (9, 'Mishi Kobe Niku', 6, 97, 324.04),
 (17, 'Alice Mutton', 6, 39, 324.04),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 324.04),
 (53, 'Perth Pasties', 6, 32.8, 324.04),
 (54, 'Tourtière', 6, 7.45, 324.04),
 (55, 'Pâté chinois', 6, 24, 324.04),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 161.85),
 (14, 'Tofu', 7, 23.25, 161.85),
 (28, 'Rössle Sauerkraut', 7, 45.6, 161.85),
 (51, 'Manjimup Dried Apples', 7, 53, 161.85),
 (74, 'Longlife Tofu', 7, 10, 161.85),
 (10, 'Ikura', 8, 31, 248.19),
 (13, 'Konbu', 8, 6, 248.19),
 (18, 'Carnarvon Tigers', 8, 62.5, 248.19),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 248.19),
 (36, 'Inlagd Sill', 8, 19, 248.19),
 (37, 'Gravad lax', 8, 26, 248.19),
 (40, 'Boston Crab Meat', 8, 18.4, 248.19),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 248.19),
 (45, 'Rogede sild', 8, 9.5, 248.19),
 (46, 'Spegesild', 8, 12, 248.19),
 (58, 'Escargots de Bourgogne', 8, 13.25, 248.19),
 (73, 'Röd Kaviar', 8, 15, 248.19)]

In [25]:
%%sql
SELECT 
    CategoryID,
    SUM(Price) AS category_total_price
FROM Products
GROUP BY CategoryID;

 * sqlite:///northwind1.db
Done.

[(1, 455.75),
 (2, 276.75),
 (3, 327.08),
 (4, 287.3),
 (5, 141.75),
 (6, 324.04),
 (7, 161.85),
 (8, 248.19)]

# 3️⃣ SUM() — Cumulative Sum within Category

In [15]:
%%sql
SELECT 
    ProductID,
    ProductName,
    CategoryID,
    Price,
    SUM(Price) OVER (
        PARTITION BY CategoryID
        ORDER BY ProductID
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS category_cumulative_price
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 18, 18),
 (2, 'Chang', 1, 19, 37),
 (24, 'Guaraná Fantástica', 1, 4.5, 41.5),
 (34, 'Sasquatch Ale', 1, 14, 55.5),
 (35, 'Steeleye Stout', 1, 18, 73.5),
 (38, 'Côte de Blaye', 1, 263.5, 337.0),
 (39, 'Chartreuse verte', 1, 18, 355.0),
 (43, 'Ipoh Coffee', 1, 46, 401.0),
 (67, 'Laughing Lumberjack Lager', 1, 14, 415.0),
 (70, 'Outback Lager', 1, 15, 430.0),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 437.75),
 (76, 'Lakkalikööri', 1, 18, 455.75),
 (3, 'Aniseed Syrup', 2, 10, 10),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 32),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 53.35),
 (6, "Grandma's Boysenberry Spread", 2, 25, 78.35),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 118.35),
 (15, 'Genen Shouyu', 2, 15.5, 133.85),
 (44, 'Gula Malacca', 2, 19.45, 153.29999999999998),
 (61, "Sirop d'érable", 2, 28.5, 181.79999999999998),
 (63, 'Vegie-spread', 2, 43.9, 225.7),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 246.75),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 263.75),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 276.75),
 (16, 'Pavlova', 3, 17.45, 17.45),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 26.65),
 (20, "Sir Rodney's Marmalade", 3, 81, 107.65),
 (21, "Sir Rodney's Scones", 3, 10, 117.65),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 131.65),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 162.88),
 (27, 'Schoggi Schokolade', 3, 43.9, 206.78),
 (47, 'Zaanse koeken', 3, 9.5, 216.28),
 (48, 'Chocolade', 3, 12.75, 229.03),
 (49, 'Maxilaku', 3, 20, 249.03),
 (50, 'Valkoinen suklaa', 3, 16.25, 265.28),
 (62, 'Tarte au sucre', 3, 49.3, 314.58),
 (68, 'Scottish Longbreads', 3, 12.5, 327.08),
 (11, 'Queso Cabrales', 4, 21, 21),
 (12, 'Queso Manchego La Pastora', 4, 38, 59),
 (31, 'Gorgonzola Telino', 4, 12.5, 71.5),
 (32, 'Mascarpone Fabioli', 4, 32, 103.5),
 (33, 'Geitost', 4, 2.5, 106.0),
 (59, 'Raclette Courdavault', 4, 55, 161.0),
 (60, 'Camembert Pierrot', 4, 34, 195.0),
 (69, 'Gudbrandsdalsost', 4, 36, 231.0),
 (71, 'Flotemysost', 4, 21.5, 252.5),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 287.3),
 (22, "Gustaf's Knäckebröd", 5, 21, 21),
 (23, 'Tunnbröd', 5, 9, 30),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 44),
 (52, 'Filo Mix', 5, 7, 51),
 (56, 'Gnocchi di nonna Alice', 5, 38, 89),
 (57, 'Ravioli Angelo', 5, 19.5, 108.5),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 141.75),
 (9, 'Mishi Kobe Niku', 6, 97, 97),
 (17, 'Alice Mutton', 6, 39, 136),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 259.79),
 (53, 'Perth Pasties', 6, 32.8, 292.59000000000003),
 (54, 'Tourtière', 6, 7.45, 300.04),
 (55, 'Pâté chinois', 6, 24, 324.04),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 30),
 (14, 'Tofu', 7, 23.25, 53.25),
 (28, 'Rössle Sauerkraut', 7, 45.6, 98.85),
 (51, 'Manjimup Dried Apples', 7, 53, 151.85),
 (74, 'Longlife Tofu', 7, 10, 161.85),
 (10, 'Ikura', 8, 31, 31),
 (13, 'Konbu', 8, 6, 37),
 (18, 'Carnarvon Tigers', 8, 62.5, 99.5),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 125.39),
 (36, 'Inlagd Sill', 8, 19, 144.39),
 (37, 'Gravad lax', 8, 26, 170.39),
 (40, 'Boston Crab Meat', 8, 18.4, 188.79),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 198.44),
 (45, 'Rogede sild', 8, 9.5, 207.94),
 (46, 'Spegesild', 8, 12, 219.94),
 (58, 'Escargots de Bourgogne', 8, 13.25, 233.19),
 (73, 'Röd Kaviar', 8, 15, 248.19)]

GROUP BY Equivalent

❌ Not directly possible with plain GROUP BY — cumulative sums require either a window function or a self-join / correlated subquery.

Example with correlated subquery:

In [28]:
%%sql
SELECT 
    p1.ProductID,
    p1.ProductName,
    p1.CategoryID,
    p1.Price,
    (
        SELECT SUM(p2.Price)
        FROM Products p2
        WHERE p2.CategoryID = p1.CategoryID
          AND p2.ProductID <= p1.ProductID
    ) AS category_cumulative_price
FROM Products p1
ORDER BY p1.CategoryID, p1.ProductID;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 18, 18),
 (2, 'Chang', 1, 19, 37),
 (24, 'Guaraná Fantástica', 1, 4.5, 41.5),
 (34, 'Sasquatch Ale', 1, 14, 55.5),
 (35, 'Steeleye Stout', 1, 18, 73.5),
 (38, 'Côte de Blaye', 1, 263.5, 337.0),
 (39, 'Chartreuse verte', 1, 18, 355.0),
 (43, 'Ipoh Coffee', 1, 46, 401.0),
 (67, 'Laughing Lumberjack Lager', 1, 14, 415.0),
 (70, 'Outback Lager', 1, 15, 430.0),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 437.75),
 (76, 'Lakkalikööri', 1, 18, 455.75),
 (3, 'Aniseed Syrup', 2, 10, 10),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 32),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 53.35),
 (6, "Grandma's Boysenberry Spread", 2, 25, 78.35),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 118.35),
 (15, 'Genen Shouyu', 2, 15.5, 133.85),
 (44, 'Gula Malacca', 2, 19.45, 153.29999999999998),
 (61, "Sirop d'érable", 2, 28.5, 181.79999999999998),
 (63, 'Vegie-spread', 2, 43.9, 225.7),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 246.75),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 263.75),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 276.75),
 (16, 'Pavlova', 3, 17.45, 17.45),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 26.65),
 (20, "Sir Rodney's Marmalade", 3, 81, 107.65),
 (21, "Sir Rodney's Scones", 3, 10, 117.65),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 131.65),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 162.88),
 (27, 'Schoggi Schokolade', 3, 43.9, 206.78),
 (47, 'Zaanse koeken', 3, 9.5, 216.28),
 (48, 'Chocolade', 3, 12.75, 229.03),
 (49, 'Maxilaku', 3, 20, 249.03),
 (50, 'Valkoinen suklaa', 3, 16.25, 265.28),
 (62, 'Tarte au sucre', 3, 49.3, 314.58),
 (68, 'Scottish Longbreads', 3, 12.5, 327.08),
 (11, 'Queso Cabrales', 4, 21, 21),
 (12, 'Queso Manchego La Pastora', 4, 38, 59),
 (31, 'Gorgonzola Telino', 4, 12.5, 71.5),
 (32, 'Mascarpone Fabioli', 4, 32, 103.5),
 (33, 'Geitost', 4, 2.5, 106.0),
 (59, 'Raclette Courdavault', 4, 55, 161.0),
 (60, 'Camembert Pierrot', 4, 34, 195.0),
 (69, 'Gudbrandsdalsost', 4, 36, 231.0),
 (71, 'Flotemysost', 4, 21.5, 252.5),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 287.3),
 (22, "Gustaf's Knäckebröd", 5, 21, 21),
 (23, 'Tunnbröd', 5, 9, 30),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 44),
 (52, 'Filo Mix', 5, 7, 51),
 (56, 'Gnocchi di nonna Alice', 5, 38, 89),
 (57, 'Ravioli Angelo', 5, 19.5, 108.5),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 141.75),
 (9, 'Mishi Kobe Niku', 6, 97, 97),
 (17, 'Alice Mutton', 6, 39, 136),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 259.79),
 (53, 'Perth Pasties', 6, 32.8, 292.59000000000003),
 (54, 'Tourtière', 6, 7.45, 300.04),
 (55, 'Pâté chinois', 6, 24, 324.04),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 30),
 (14, 'Tofu', 7, 23.25, 53.25),
 (28, 'Rössle Sauerkraut', 7, 45.6, 98.85),
 (51, 'Manjimup Dried Apples', 7, 53, 151.85),
 (74, 'Longlife Tofu', 7, 10, 161.85),
 (10, 'Ikura', 8, 31, 31),
 (13, 'Konbu', 8, 6, 37),
 (18, 'Carnarvon Tigers', 8, 62.5, 99.5),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 125.39),
 (36, 'Inlagd Sill', 8, 19, 144.39),
 (37, 'Gravad lax', 8, 26, 170.39),
 (40, 'Boston Crab Meat', 8, 18.4, 188.79),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 198.44),
 (45, 'Rogede sild', 8, 9.5, 207.94),
 (46, 'Spegesild', 8, 12, 219.94),
 (58, 'Escargots de Bourgogne', 8, 13.25, 233.19),
 (73, 'Röd Kaviar', 8, 15, 248.19)]

# 4️⃣ AVG() — Average Price Across All Products

In [16]:
%%sql
SELECT 
    ProductID,
    ProductName,
    Price,
    AVG(Price) OVER () AS avg_price_all_products
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 18, 28.866363636363637),
 (2, 'Chang', 19, 28.866363636363637),
 (3, 'Aniseed Syrup', 10, 28.866363636363637),
 (4, "Chef Anton's Cajun Seasoning", 22, 28.866363636363637),
 (5, "Chef Anton's Gumbo Mix", 21.35, 28.866363636363637),
 (6, "Grandma's Boysenberry Spread", 25, 28.866363636363637),
 (7, "Uncle Bob's Organic Dried Pears", 30, 28.866363636363637),
 (8, 'Northwoods Cranberry Sauce', 40, 28.866363636363637),
 (9, 'Mishi Kobe Niku', 97, 28.866363636363637),
 (10, 'Ikura', 31, 28.866363636363637),
 (11, 'Queso Cabrales', 21, 28.866363636363637),
 (12, 'Queso Manchego La Pastora', 38, 28.866363636363637),
 (13, 'Konbu', 6, 28.866363636363637),
 (14, 'Tofu', 23.25, 28.866363636363637),
 (15, 'Genen Shouyu', 15.5, 28.866363636363637),
 (16, 'Pavlova', 17.45, 28.866363636363637),
 (17, 'Alice Mutton', 39, 28.866363636363637),
 (18, 'Carnarvon Tigers', 62.5, 28.866363636363637),
 (19, 'Teatime Chocolate Biscuits', 9.2, 28.866363636363637),
 (20, "Sir Rodney's Marmalade", 81, 28.866363636363637),
 (21, "Sir Rodney's Scones", 10, 28.866363636363637),
 (22, "Gustaf's Knäckebröd", 21, 28.866363636363637),
 (23, 'Tunnbröd', 9, 28.866363636363637),
 (24, 'Guaraná Fantástica', 4.5, 28.866363636363637),
 (25, 'NuNuCa Nuß-Nougat-Creme', 14, 28.866363636363637),
 (26, 'Gumbär Gummibärchen', 31.23, 28.866363636363637),
 (27, 'Schoggi Schokolade', 43.9, 28.866363636363637),
 (28, 'Rössle Sauerkraut', 45.6, 28.866363636363637),
 (29, 'Thüringer Rostbratwurst', 123.79, 28.866363636363637),
 (30, 'Nord-Ost Matjeshering', 25.89, 28.866363636363637),
 (31, 'Gorgonzola Telino', 12.5, 28.866363636363637),
 (32, 'Mascarpone Fabioli', 32, 28.866363636363637),
 (33, 'Geitost', 2.5, 28.866363636363637),
 (34, 'Sasquatch Ale', 14, 28.866363636363637),
 (35, 'Steeleye Stout', 18, 28.866363636363637),
 (36, 'Inlagd Sill', 19, 28.866363636363637),
 (37, 'Gravad lax', 26, 28.866363636363637),
 (38, 'Côte de Blaye', 263.5, 28.866363636363637),
 (39, 'Chartreuse verte', 18, 28.866363636363637),
 (40, 'Boston Crab Meat', 18.4, 28.866363636363637),
 (41, "Jack's New England Clam Chowder", 9.65, 28.866363636363637),
 (42, 'Singaporean Hokkien Fried Mee', 14, 28.866363636363637),
 (43, 'Ipoh Coffee', 46, 28.866363636363637),
 (44, 'Gula Malacca', 19.45, 28.866363636363637),
 (45, 'Rogede sild', 9.5, 28.866363636363637),
 (46, 'Spegesild', 12, 28.866363636363637),
 (47, 'Zaanse koeken', 9.5, 28.866363636363637),
 (48, 'Chocolade', 12.75, 28.866363636363637),
 (49, 'Maxilaku', 20, 28.866363636363637),
 (50, 'Valkoinen suklaa', 16.25, 28.866363636363637),
 (51, 'Manjimup Dried Apples', 53, 28.866363636363637),
 (52, 'Filo Mix', 7, 28.866363636363637),
 (53, 'Perth Pasties', 32.8, 28.866363636363637),
 (54, 'Tourtière', 7.45, 28.866363636363637),
 (55, 'Pâté chinois', 24, 28.866363636363637),
 (56, 'Gnocchi di nonna Alice', 38, 28.866363636363637),
 (57, 'Ravioli Angelo', 19.5, 28.866363636363637),
 (58, 'Escargots de Bourgogne', 13.25, 28.866363636363637),
 (59, 'Raclette Courdavault', 55, 28.866363636363637),
 (60, 'Camembert Pierrot', 34, 28.866363636363637),
 (61, "Sirop d'érable", 28.5, 28.866363636363637),
 (62, 'Tarte au sucre', 49.3, 28.866363636363637),
 (63, 'Vegie-spread', 43.9, 28.866363636363637),
 (64, 'Wimmers gute Semmelknödel', 33.25, 28.866363636363637),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 21.05, 28.866363636363637),
 (66, 'Louisiana Hot Spiced Okra', 17, 28.866363636363637),
 (67, 'Laughing Lumberjack Lager', 14, 28.866363636363637),
 (68, 'Scottish Longbreads', 12.5, 28.866363636363637),
 (69, 'Gudbrandsdalsost', 36, 28.866363636363637),
 (70, 'Outback Lager', 15, 28.866363636363637),
 (71, 'Flotemysost', 21.5, 28.866363636363637),
 (72, 'Mozzarella di Giovanni', 34.8, 28.866363636363637),
 (73, 'Röd Kaviar', 15, 28.866363636363637),
 (74, 'Longlife Tofu', 10, 28.866363636363637),
 (75, 'Rhönbräu Klosterbier', 7.75, 28.866363636363637),
 (76, 'Lakkalikööri', 18, 28.866363636363637),
 (77, 'Original Frankfurter grüne Soße', 13, 28.866363636363637)]

In [29]:
%%sql
SELECT 
    ProductID,
    ProductName,
    Price,
    AVG(Price) OVER () AS avg_price_all_products
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 18, 28.866363636363637),
 (2, 'Chang', 19, 28.866363636363637),
 (3, 'Aniseed Syrup', 10, 28.866363636363637),
 (4, "Chef Anton's Cajun Seasoning", 22, 28.866363636363637),
 (5, "Chef Anton's Gumbo Mix", 21.35, 28.866363636363637),
 (6, "Grandma's Boysenberry Spread", 25, 28.866363636363637),
 (7, "Uncle Bob's Organic Dried Pears", 30, 28.866363636363637),
 (8, 'Northwoods Cranberry Sauce', 40, 28.866363636363637),
 (9, 'Mishi Kobe Niku', 97, 28.866363636363637),
 (10, 'Ikura', 31, 28.866363636363637),
 (11, 'Queso Cabrales', 21, 28.866363636363637),
 (12, 'Queso Manchego La Pastora', 38, 28.866363636363637),
 (13, 'Konbu', 6, 28.866363636363637),
 (14, 'Tofu', 23.25, 28.866363636363637),
 (15, 'Genen Shouyu', 15.5, 28.866363636363637),
 (16, 'Pavlova', 17.45, 28.866363636363637),
 (17, 'Alice Mutton', 39, 28.866363636363637),
 (18, 'Carnarvon Tigers', 62.5, 28.866363636363637),
 (19, 'Teatime Chocolate Biscuits', 9.2, 28.866363636363637),
 (20, "Sir Rodney's Marmalade", 81, 28.866363636363637),
 (21, "Sir Rodney's Scones", 10, 28.866363636363637),
 (22, "Gustaf's Knäckebröd", 21, 28.866363636363637),
 (23, 'Tunnbröd', 9, 28.866363636363637),
 (24, 'Guaraná Fantástica', 4.5, 28.866363636363637),
 (25, 'NuNuCa Nuß-Nougat-Creme', 14, 28.866363636363637),
 (26, 'Gumbär Gummibärchen', 31.23, 28.866363636363637),
 (27, 'Schoggi Schokolade', 43.9, 28.866363636363637),
 (28, 'Rössle Sauerkraut', 45.6, 28.866363636363637),
 (29, 'Thüringer Rostbratwurst', 123.79, 28.866363636363637),
 (30, 'Nord-Ost Matjeshering', 25.89, 28.866363636363637),
 (31, 'Gorgonzola Telino', 12.5, 28.866363636363637),
 (32, 'Mascarpone Fabioli', 32, 28.866363636363637),
 (33, 'Geitost', 2.5, 28.866363636363637),
 (34, 'Sasquatch Ale', 14, 28.866363636363637),
 (35, 'Steeleye Stout', 18, 28.866363636363637),
 (36, 'Inlagd Sill', 19, 28.866363636363637),
 (37, 'Gravad lax', 26, 28.866363636363637),
 (38, 'Côte de Blaye', 263.5, 28.866363636363637),
 (39, 'Chartreuse verte', 18, 28.866363636363637),
 (40, 'Boston Crab Meat', 18.4, 28.866363636363637),
 (41, "Jack's New England Clam Chowder", 9.65, 28.866363636363637),
 (42, 'Singaporean Hokkien Fried Mee', 14, 28.866363636363637),
 (43, 'Ipoh Coffee', 46, 28.866363636363637),
 (44, 'Gula Malacca', 19.45, 28.866363636363637),
 (45, 'Rogede sild', 9.5, 28.866363636363637),
 (46, 'Spegesild', 12, 28.866363636363637),
 (47, 'Zaanse koeken', 9.5, 28.866363636363637),
 (48, 'Chocolade', 12.75, 28.866363636363637),
 (49, 'Maxilaku', 20, 28.866363636363637),
 (50, 'Valkoinen suklaa', 16.25, 28.866363636363637),
 (51, 'Manjimup Dried Apples', 53, 28.866363636363637),
 (52, 'Filo Mix', 7, 28.866363636363637),
 (53, 'Perth Pasties', 32.8, 28.866363636363637),
 (54, 'Tourtière', 7.45, 28.866363636363637),
 (55, 'Pâté chinois', 24, 28.866363636363637),
 (56, 'Gnocchi di nonna Alice', 38, 28.866363636363637),
 (57, 'Ravioli Angelo', 19.5, 28.866363636363637),
 (58, 'Escargots de Bourgogne', 13.25, 28.866363636363637),
 (59, 'Raclette Courdavault', 55, 28.866363636363637),
 (60, 'Camembert Pierrot', 34, 28.866363636363637),
 (61, "Sirop d'érable", 28.5, 28.866363636363637),
 (62, 'Tarte au sucre', 49.3, 28.866363636363637),
 (63, 'Vegie-spread', 43.9, 28.866363636363637),
 (64, 'Wimmers gute Semmelknödel', 33.25, 28.866363636363637),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 21.05, 28.866363636363637),
 (66, 'Louisiana Hot Spiced Okra', 17, 28.866363636363637),
 (67, 'Laughing Lumberjack Lager', 14, 28.866363636363637),
 (68, 'Scottish Longbreads', 12.5, 28.866363636363637),
 (69, 'Gudbrandsdalsost', 36, 28.866363636363637),
 (70, 'Outback Lager', 15, 28.866363636363637),
 (71, 'Flotemysost', 21.5, 28.866363636363637),
 (72, 'Mozzarella di Giovanni', 34.8, 28.866363636363637),
 (73, 'Röd Kaviar', 15, 28.866363636363637),
 (74, 'Longlife Tofu', 10, 28.866363636363637),
 (75, 'Rhönbräu Klosterbier', 7.75, 28.866363636363637),
 (76, 'Lakkalikööri', 18, 28.866363636363637),
 (77, 'Original Frankfurter grüne Soße', 13, 28.866363636363637)]

# 5️⃣ AVG() — Average Price per Category

In [19]:
%%sql
SELECT 
    ProductID,
    ProductName,
    CategoryID,
    Price,
    AVG(Price) OVER (PARTITION BY CategoryID) AS avg_price_per_category
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 18, 37.979166666666664),
 (2, 'Chang', 1, 19, 37.979166666666664),
 (24, 'Guaraná Fantástica', 1, 4.5, 37.979166666666664),
 (34, 'Sasquatch Ale', 1, 14, 37.979166666666664),
 (35, 'Steeleye Stout', 1, 18, 37.979166666666664),
 (38, 'Côte de Blaye', 1, 263.5, 37.979166666666664),
 (39, 'Chartreuse verte', 1, 18, 37.979166666666664),
 (43, 'Ipoh Coffee', 1, 46, 37.979166666666664),
 (67, 'Laughing Lumberjack Lager', 1, 14, 37.979166666666664),
 (70, 'Outback Lager', 1, 15, 37.979166666666664),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 37.979166666666664),
 (76, 'Lakkalikööri', 1, 18, 37.979166666666664),
 (3, 'Aniseed Syrup', 2, 10, 23.0625),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 23.0625),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 23.0625),
 (6, "Grandma's Boysenberry Spread", 2, 25, 23.0625),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 23.0625),
 (15, 'Genen Shouyu', 2, 15.5, 23.0625),
 (44, 'Gula Malacca', 2, 19.45, 23.0625),
 (61, "Sirop d'érable", 2, 28.5, 23.0625),
 (63, 'Vegie-spread', 2, 43.9, 23.0625),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 23.0625),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 23.0625),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 23.0625),
 (16, 'Pavlova', 3, 17.45, 25.16),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 25.16),
 (20, "Sir Rodney's Marmalade", 3, 81, 25.16),
 (21, "Sir Rodney's Scones", 3, 10, 25.16),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 25.16),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 25.16),
 (27, 'Schoggi Schokolade', 3, 43.9, 25.16),
 (47, 'Zaanse koeken', 3, 9.5, 25.16),
 (48, 'Chocolade', 3, 12.75, 25.16),
 (49, 'Maxilaku', 3, 20, 25.16),
 (50, 'Valkoinen suklaa', 3, 16.25, 25.16),
 (62, 'Tarte au sucre', 3, 49.3, 25.16),
 (68, 'Scottish Longbreads', 3, 12.5, 25.16),
 (11, 'Queso Cabrales', 4, 21, 28.73),
 (12, 'Queso Manchego La Pastora', 4, 38, 28.73),
 (31, 'Gorgonzola Telino', 4, 12.5, 28.73),
 (32, 'Mascarpone Fabioli', 4, 32, 28.73),
 (33, 'Geitost', 4, 2.5, 28.73),
 (59, 'Raclette Courdavault', 4, 55, 28.73),
 (60, 'Camembert Pierrot', 4, 34, 28.73),
 (69, 'Gudbrandsdalsost', 4, 36, 28.73),
 (71, 'Flotemysost', 4, 21.5, 28.73),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 28.73),
 (22, "Gustaf's Knäckebröd", 5, 21, 20.25),
 (23, 'Tunnbröd', 5, 9, 20.25),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 20.25),
 (52, 'Filo Mix', 5, 7, 20.25),
 (56, 'Gnocchi di nonna Alice', 5, 38, 20.25),
 (57, 'Ravioli Angelo', 5, 19.5, 20.25),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 20.25),
 (9, 'Mishi Kobe Niku', 6, 97, 54.00666666666667),
 (17, 'Alice Mutton', 6, 39, 54.00666666666667),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 54.00666666666667),
 (53, 'Perth Pasties', 6, 32.8, 54.00666666666667),
 (54, 'Tourtière', 6, 7.45, 54.00666666666667),
 (55, 'Pâté chinois', 6, 24, 54.00666666666667),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 32.37),
 (14, 'Tofu', 7, 23.25, 32.37),
 (28, 'Rössle Sauerkraut', 7, 45.6, 32.37),
 (51, 'Manjimup Dried Apples', 7, 53, 32.37),
 (74, 'Longlife Tofu', 7, 10, 32.37),
 (10, 'Ikura', 8, 31, 20.6825),
 (13, 'Konbu', 8, 6, 20.6825),
 (18, 'Carnarvon Tigers', 8, 62.5, 20.6825),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 20.6825),
 (36, 'Inlagd Sill', 8, 19, 20.6825),
 (37, 'Gravad lax', 8, 26, 20.6825),
 (40, 'Boston Crab Meat', 8, 18.4, 20.6825),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 20.6825),
 (45, 'Rogede sild', 8, 9.5, 20.6825),
 (46, 'Spegesild', 8, 12, 20.6825),
 (58, 'Escargots de Bourgogne', 8, 13.25, 20.6825),
 (73, 'Röd Kaviar', 8, 15, 20.6825)]

In [30]:
%%sql
SELECT 
    CategoryID,
    AVG(Price) AS avg_price_per_category
FROM Products
GROUP BY CategoryID;

 * sqlite:///northwind1.db
Done.

[(1, 37.979166666666664),
 (2, 23.0625),
 (3, 25.16),
 (4, 28.73),
 (5, 20.25),
 (6, 54.00666666666667),
 (7, 32.37),
 (8, 20.6825)]

# 6️⃣ MIN() and MAX() — Price Range per Category

In [20]:
%%sql
SELECT 
    ProductID,
    ProductName,
    CategoryID,
    Price,
    MIN(Price) OVER (PARTITION BY CategoryID) AS min_price_in_category,
    MAX(Price) OVER (PARTITION BY CategoryID) AS max_price_in_category
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 18, 4.5, 263.5),
 (2, 'Chang', 1, 19, 4.5, 263.5),
 (24, 'Guaraná Fantástica', 1, 4.5, 4.5, 263.5),
 (34, 'Sasquatch Ale', 1, 14, 4.5, 263.5),
 (35, 'Steeleye Stout', 1, 18, 4.5, 263.5),
 (38, 'Côte de Blaye', 1, 263.5, 4.5, 263.5),
 (39, 'Chartreuse verte', 1, 18, 4.5, 263.5),
 (43, 'Ipoh Coffee', 1, 46, 4.5, 263.5),
 (67, 'Laughing Lumberjack Lager', 1, 14, 4.5, 263.5),
 (70, 'Outback Lager', 1, 15, 4.5, 263.5),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 4.5, 263.5),
 (76, 'Lakkalikööri', 1, 18, 4.5, 263.5),
 (3, 'Aniseed Syrup', 2, 10, 10, 43.9),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 10, 43.9),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 10, 43.9),
 (6, "Grandma's Boysenberry Spread", 2, 25, 10, 43.9),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 10, 43.9),
 (15, 'Genen Shouyu', 2, 15.5, 10, 43.9),
 (44, 'Gula Malacca', 2, 19.45, 10, 43.9),
 (61, "Sirop d'érable", 2, 28.5, 10, 43.9),
 (63, 'Vegie-spread', 2, 43.9, 10, 43.9),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 10, 43.9),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 10, 43.9),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 10, 43.9),
 (16, 'Pavlova', 3, 17.45, 9.2, 81),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 9.2, 81),
 (20, "Sir Rodney's Marmalade", 3, 81, 9.2, 81),
 (21, "Sir Rodney's Scones", 3, 10, 9.2, 81),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 9.2, 81),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 9.2, 81),
 (27, 'Schoggi Schokolade', 3, 43.9, 9.2, 81),
 (47, 'Zaanse koeken', 3, 9.5, 9.2, 81),
 (48, 'Chocolade', 3, 12.75, 9.2, 81),
 (49, 'Maxilaku', 3, 20, 9.2, 81),
 (50, 'Valkoinen suklaa', 3, 16.25, 9.2, 81),
 (62, 'Tarte au sucre', 3, 49.3, 9.2, 81),
 (68, 'Scottish Longbreads', 3, 12.5, 9.2, 81),
 (11, 'Queso Cabrales', 4, 21, 2.5, 55),
 (12, 'Queso Manchego La Pastora', 4, 38, 2.5, 55),
 (31, 'Gorgonzola Telino', 4, 12.5, 2.5, 55),
 (32, 'Mascarpone Fabioli', 4, 32, 2.5, 55),
 (33, 'Geitost', 4, 2.5, 2.5, 55),
 (59, 'Raclette Courdavault', 4, 55, 2.5, 55),
 (60, 'Camembert Pierrot', 4, 34, 2.5, 55),
 (69, 'Gudbrandsdalsost', 4, 36, 2.5, 55),
 (71, 'Flotemysost', 4, 21.5, 2.5, 55),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 2.5, 55),
 (22, "Gustaf's Knäckebröd", 5, 21, 7, 38),
 (23, 'Tunnbröd', 5, 9, 7, 38),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 7, 38),
 (52, 'Filo Mix', 5, 7, 7, 38),
 (56, 'Gnocchi di nonna Alice', 5, 38, 7, 38),
 (57, 'Ravioli Angelo', 5, 19.5, 7, 38),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 7, 38),
 (9, 'Mishi Kobe Niku', 6, 97, 7.45, 123.79),
 (17, 'Alice Mutton', 6, 39, 7.45, 123.79),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 7.45, 123.79),
 (53, 'Perth Pasties', 6, 32.8, 7.45, 123.79),
 (54, 'Tourtière', 6, 7.45, 7.45, 123.79),
 (55, 'Pâté chinois', 6, 24, 7.45, 123.79),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 10, 53),
 (14, 'Tofu', 7, 23.25, 10, 53),
 (28, 'Rössle Sauerkraut', 7, 45.6, 10, 53),
 (51, 'Manjimup Dried Apples', 7, 53, 10, 53),
 (74, 'Longlife Tofu', 7, 10, 10, 53),
 (10, 'Ikura', 8, 31, 6, 62.5),
 (13, 'Konbu', 8, 6, 6, 62.5),
 (18, 'Carnarvon Tigers', 8, 62.5, 6, 62.5),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 6, 62.5),
 (36, 'Inlagd Sill', 8, 19, 6, 62.5),
 (37, 'Gravad lax', 8, 26, 6, 62.5),
 (40, 'Boston Crab Meat', 8, 18.4, 6, 62.5),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 6, 62.5),
 (45, 'Rogede sild', 8, 9.5, 6, 62.5),
 (46, 'Spegesild', 8, 12, 6, 62.5),
 (58, 'Escargots de Bourgogne', 8, 13.25, 6, 62.5),
 (73, 'Röd Kaviar', 8, 15, 6, 62.5)]

In [32]:
%%sql
SELECT 
    CategoryID,
    MIN(Price) AS min_price_in_category,
    MAX(Price) AS max_price_in_category
FROM Products
GROUP BY CategoryID;

 * sqlite:///northwind1.db
Done.

[(1, 4.5, 263.5),
 (2, 10, 43.9),
 (3, 9.2, 81),
 (4, 2.5, 55),
 (5, 7, 38),
 (6, 7.45, 123.79),
 (7, 10, 53),
 (8, 6, 62.5)]

# 7️⃣ COUNT() — Number of Products per Category

In [21]:
%%sql
SELECT 
    ProductID,
    ProductName,
    CategoryID,
    Price,
    COUNT(*) OVER (PARTITION BY CategoryID) AS product_count_in_category
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 18, 12),
 (2, 'Chang', 1, 19, 12),
 (24, 'Guaraná Fantástica', 1, 4.5, 12),
 (34, 'Sasquatch Ale', 1, 14, 12),
 (35, 'Steeleye Stout', 1, 18, 12),
 (38, 'Côte de Blaye', 1, 263.5, 12),
 (39, 'Chartreuse verte', 1, 18, 12),
 (43, 'Ipoh Coffee', 1, 46, 12),
 (67, 'Laughing Lumberjack Lager', 1, 14, 12),
 (70, 'Outback Lager', 1, 15, 12),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 12),
 (76, 'Lakkalikööri', 1, 18, 12),
 (3, 'Aniseed Syrup', 2, 10, 12),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 12),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 12),
 (6, "Grandma's Boysenberry Spread", 2, 25, 12),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 12),
 (15, 'Genen Shouyu', 2, 15.5, 12),
 (44, 'Gula Malacca', 2, 19.45, 12),
 (61, "Sirop d'érable", 2, 28.5, 12),
 (63, 'Vegie-spread', 2, 43.9, 12),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 12),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 12),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 12),
 (16, 'Pavlova', 3, 17.45, 13),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 13),
 (20, "Sir Rodney's Marmalade", 3, 81, 13),
 (21, "Sir Rodney's Scones", 3, 10, 13),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 13),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 13),
 (27, 'Schoggi Schokolade', 3, 43.9, 13),
 (47, 'Zaanse koeken', 3, 9.5, 13),
 (48, 'Chocolade', 3, 12.75, 13),
 (49, 'Maxilaku', 3, 20, 13),
 (50, 'Valkoinen suklaa', 3, 16.25, 13),
 (62, 'Tarte au sucre', 3, 49.3, 13),
 (68, 'Scottish Longbreads', 3, 12.5, 13),
 (11, 'Queso Cabrales', 4, 21, 10),
 (12, 'Queso Manchego La Pastora', 4, 38, 10),
 (31, 'Gorgonzola Telino', 4, 12.5, 10),
 (32, 'Mascarpone Fabioli', 4, 32, 10),
 (33, 'Geitost', 4, 2.5, 10),
 (59, 'Raclette Courdavault', 4, 55, 10),
 (60, 'Camembert Pierrot', 4, 34, 10),
 (69, 'Gudbrandsdalsost', 4, 36, 10),
 (71, 'Flotemysost', 4, 21.5, 10),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 10),
 (22, "Gustaf's Knäckebröd", 5, 21, 7),
 (23, 'Tunnbröd', 5, 9, 7),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 7),
 (52, 'Filo Mix', 5, 7, 7),
 (56, 'Gnocchi di nonna Alice', 5, 38, 7),
 (57, 'Ravioli Angelo', 5, 19.5, 7),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 7),
 (9, 'Mishi Kobe Niku', 6, 97, 6),
 (17, 'Alice Mutton', 6, 39, 6),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 6),
 (53, 'Perth Pasties', 6, 32.8, 6),
 (54, 'Tourtière', 6, 7.45, 6),
 (55, 'Pâté chinois', 6, 24, 6),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 5),
 (14, 'Tofu', 7, 23.25, 5),
 (28, 'Rössle Sauerkraut', 7, 45.6, 5),
 (51, 'Manjimup Dried Apples', 7, 53, 5),
 (74, 'Longlife Tofu', 7, 10, 5),
 (10, 'Ikura', 8, 31, 12),
 (13, 'Konbu', 8, 6, 12),
 (18, 'Carnarvon Tigers', 8, 62.5, 12),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 12),
 (36, 'Inlagd Sill', 8, 19, 12),
 (37, 'Gravad lax', 8, 26, 12),
 (40, 'Boston Crab Meat', 8, 18.4, 12),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 12),
 (45, 'Rogede sild', 8, 9.5, 12),
 (46, 'Spegesild', 8, 12, 12),
 (58, 'Escargots de Bourgogne', 8, 13.25, 12),
 (73, 'Röd Kaviar', 8, 15, 12)]

In [33]:
%%sql
SELECT 
    CategoryID,
    COUNT(*) AS product_count_in_category
FROM Products
GROUP BY CategoryID;

 * sqlite:///northwind1.db
Done.

[(1, 12), (2, 12), (3, 13), (4, 10), (5, 7), (6, 6), (7, 5), (8, 12)]

# 8️⃣ Combining Multiple Window Aggregates

In [22]:
%%sql
SELECT 
    ProductID,
    ProductName,
    CategoryID,
    Price,
    COUNT(*) OVER (PARTITION BY CategoryID) AS product_count,
    SUM(Price) OVER (PARTITION BY CategoryID) AS total_price,
    AVG(Price) OVER (PARTITION BY CategoryID) AS avg_price,
    MIN(Price) OVER (PARTITION BY CategoryID) AS min_price,
    MAX(Price) OVER (PARTITION BY CategoryID) AS max_price
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 18, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (2, 'Chang', 1, 19, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (24, 'Guaraná Fantástica', 1, 4.5, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (34, 'Sasquatch Ale', 1, 14, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (35, 'Steeleye Stout', 1, 18, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (38, 'Côte de Blaye', 1, 263.5, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (39, 'Chartreuse verte', 1, 18, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (43, 'Ipoh Coffee', 1, 46, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (67, 'Laughing Lumberjack Lager', 1, 14, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (70, 'Outback Lager', 1, 15, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (76, 'Lakkalikööri', 1, 18, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (3, 'Aniseed Syrup', 2, 10, 12, 276.75, 23.0625, 10, 43.9),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 12, 276.75, 23.0625, 10, 43.9),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 12, 276.75, 23.0625, 10, 43.9),
 (6, "Grandma's Boysenberry Spread", 2, 25, 12, 276.75, 23.0625, 10, 43.9),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 12, 276.75, 23.0625, 10, 43.9),
 (15, 'Genen Shouyu', 2, 15.5, 12, 276.75, 23.0625, 10, 43.9),
 (44, 'Gula Malacca', 2, 19.45, 12, 276.75, 23.0625, 10, 43.9),
 (61, "Sirop d'érable", 2, 28.5, 12, 276.75, 23.0625, 10, 43.9),
 (63, 'Vegie-spread', 2, 43.9, 12, 276.75, 23.0625, 10, 43.9),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 12, 276.75, 23.0625, 10, 43.9),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 12, 276.75, 23.0625, 10, 43.9),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 12, 276.75, 23.0625, 10, 43.9),
 (16, 'Pavlova', 3, 17.45, 13, 327.08, 25.16, 9.2, 81),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 13, 327.08, 25.16, 9.2, 81),
 (20, "Sir Rodney's Marmalade", 3, 81, 13, 327.08, 25.16, 9.2, 81),
 (21, "Sir Rodney's Scones", 3, 10, 13, 327.08, 25.16, 9.2, 81),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 13, 327.08, 25.16, 9.2, 81),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 13, 327.08, 25.16, 9.2, 81),
 (27, 'Schoggi Schokolade', 3, 43.9, 13, 327.08, 25.16, 9.2, 81),
 (47, 'Zaanse koeken', 3, 9.5, 13, 327.08, 25.16, 9.2, 81),
 (48, 'Chocolade', 3, 12.75, 13, 327.08, 25.16, 9.2, 81),
 (49, 'Maxilaku', 3, 20, 13, 327.08, 25.16, 9.2, 81),
 (50, 'Valkoinen suklaa', 3, 16.25, 13, 327.08, 25.16, 9.2, 81),
 (62, 'Tarte au sucre', 3, 49.3, 13, 327.08, 25.16, 9.2, 81),
 (68, 'Scottish Longbreads', 3, 12.5, 13, 327.08, 25.16, 9.2, 81),
 (11, 'Queso Cabrales', 4, 21, 10, 287.3, 28.73, 2.5, 55),
 (12, 'Queso Manchego La Pastora', 4, 38, 10, 287.3, 28.73, 2.5, 55),
 (31, 'Gorgonzola Telino', 4, 12.5, 10, 287.3, 28.73, 2.5, 55),
 (32, 'Mascarpone Fabioli', 4, 32, 10, 287.3, 28.73, 2.5, 55),
 (33, 'Geitost', 4, 2.5, 10, 287.3, 28.73, 2.5, 55),
 (59, 'Raclette Courdavault', 4, 55, 10, 287.3, 28.73, 2.5, 55),
 (60, 'Camembert Pierrot', 4, 34, 10, 287.3, 28.73, 2.5, 55),
 (69, 'Gudbrandsdalsost', 4, 36, 10, 287.3, 28.73, 2.5, 55),
 (71, 'Flotemysost', 4, 21.5, 10, 287.3, 28.73, 2.5, 55),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 10, 287.3, 28.73, 2.5, 55),
 (22, "Gustaf's Knäckebröd", 5, 21, 7, 141.75, 20.25, 7, 38),
 (23, 'Tunnbröd', 5, 9, 7, 141.75, 20.25, 7, 38),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 7, 141.75, 20.25, 7, 38),
 (52, 'Filo Mix', 5, 7, 7, 141.75, 20.25, 7, 38),
 (56, 'Gnocchi di nonna Alice', 5, 38, 7, 141.75, 20.25, 7, 38),
 (57, 'Ravioli Angelo', 5, 19.5, 7, 141.75, 20.25, 7, 38),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 7, 141.75, 20.25, 7, 38),
 (9, 'Mishi Kobe Niku', 6, 97, 6, 324.04, 54.00666666666667, 7.45, 123.79),
 (17, 'Alice Mutton', 6, 39, 6, 324.04, 54.00666666666667, 7.45, 123.79),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 6, 324.04, 54.00666666666667, 7.45, 123.79),
 (53, 'Perth Pasties', 6, 32.8, 6, 324.04, 54.00666666666667, 7.45, 123.79),
 (54, 'Tourtière', 6, 7.45, 6, 324.04, 54.00666666666667, 7.45, 123.79),
 (55, 'Pâté chinois', 6, 24, 6, 324.04, 54.00666666666667, 7.45, 123.79),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 5, 161.85, 32.37, 10, 53),
 (14, 'Tofu', 7, 23.25, 5, 161.85, 32.37, 10, 53),
 (28, 'Rössle Sauerkraut', 7, 45.6, 5, 161.85, 32.37, 10, 53),
 (51, 'Manjimup Dried Apples', 7, 53, 5, 161.85, 32.37, 10, 53),
 (74, 'Longlife Tofu', 7, 10, 5, 161.85, 32.37, 10, 53),
 (10, 'Ikura', 8, 31, 12, 248.19, 20.6825, 6, 62.5),
 (13, 'Konbu', 8, 6, 12, 248.19, 20.6825, 6, 62.5),
 (18, 'Carnarvon Tigers', 8, 62.5, 12, 248.19, 20.6825, 6, 62.5),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 12, 248.19, 20.6825, 6, 62.5),
 (36, 'Inlagd Sill', 8, 19, 12, 248.19, 20.6825, 6, 62.5),
 (37, 'Gravad lax', 8, 26, 12, 248.19, 20.6825, 6, 62.5),
 (40, 'Boston Crab Meat', 8, 18.4, 12, 248.19, 20.6825, 6, 62.5),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 12, 248.19, 20.6825, 6, 62.5),
 (45, 'Rogede sild', 8, 9.5, 12, 248.19, 20.6825, 6, 62.5),
 (46, 'Spegesild', 8, 12, 12, 248.19, 20.6825, 6, 62.5),
 (58, 'Escargots de Bourgogne', 8, 13.25, 12, 248.19, 20.6825, 6, 62.5),
 (73, 'Röd Kaviar', 8, 15, 12, 248.19, 20.6825, 6, 62.5)]

In [34]:
%%sql
SELECT 
    CategoryID,
    COUNT(*) AS product_count,
    SUM(Price) AS total_price,
    AVG(Price) AS avg_price,
    MIN(Price) AS min_price,
    MAX(Price) AS max_price
FROM Products
GROUP BY CategoryID;

 * sqlite:///northwind1.db
Done.

[(1, 12, 455.75, 37.979166666666664, 4.5, 263.5),
 (2, 12, 276.75, 23.0625, 10, 43.9),
 (3, 13, 327.08, 25.16, 9.2, 81),
 (4, 10, 287.3, 28.73, 2.5, 55),
 (5, 7, 141.75, 20.25, 7, 38),
 (6, 6, 324.04, 54.00666666666667, 7.45, 123.79),
 (7, 5, 161.85, 32.37, 10, 53),
 (8, 12, 248.19, 20.6825, 6, 62.5)]

# 9️⃣ COUNT() with Running Count (ROW-Like Behavior)

In [23]:
%%sql
SELECT 
    ProductID,
    ProductName,
    CategoryID,
    Price,
    COUNT(*) OVER (
        PARTITION BY CategoryID
        ORDER BY ProductID
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS running_product_count
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 18, 1),
 (2, 'Chang', 1, 19, 2),
 (24, 'Guaraná Fantástica', 1, 4.5, 3),
 (34, 'Sasquatch Ale', 1, 14, 4),
 (35, 'Steeleye Stout', 1, 18, 5),
 (38, 'Côte de Blaye', 1, 263.5, 6),
 (39, 'Chartreuse verte', 1, 18, 7),
 (43, 'Ipoh Coffee', 1, 46, 8),
 (67, 'Laughing Lumberjack Lager', 1, 14, 9),
 (70, 'Outback Lager', 1, 15, 10),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 11),
 (76, 'Lakkalikööri', 1, 18, 12),
 (3, 'Aniseed Syrup', 2, 10, 1),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 2),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 3),
 (6, "Grandma's Boysenberry Spread", 2, 25, 4),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 5),
 (15, 'Genen Shouyu', 2, 15.5, 6),
 (44, 'Gula Malacca', 2, 19.45, 7),
 (61, "Sirop d'érable", 2, 28.5, 8),
 (63, 'Vegie-spread', 2, 43.9, 9),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 10),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 11),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 12),
 (16, 'Pavlova', 3, 17.45, 1),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 2),
 (20, "Sir Rodney's Marmalade", 3, 81, 3),
 (21, "Sir Rodney's Scones", 3, 10, 4),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 5),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 6),
 (27, 'Schoggi Schokolade', 3, 43.9, 7),
 (47, 'Zaanse koeken', 3, 9.5, 8),
 (48, 'Chocolade', 3, 12.75, 9),
 (49, 'Maxilaku', 3, 20, 10),
 (50, 'Valkoinen suklaa', 3, 16.25, 11),
 (62, 'Tarte au sucre', 3, 49.3, 12),
 (68, 'Scottish Longbreads', 3, 12.5, 13),
 (11, 'Queso Cabrales', 4, 21, 1),
 (12, 'Queso Manchego La Pastora', 4, 38, 2),
 (31, 'Gorgonzola Telino', 4, 12.5, 3),
 (32, 'Mascarpone Fabioli', 4, 32, 4),
 (33, 'Geitost', 4, 2.5, 5),
 (59, 'Raclette Courdavault', 4, 55, 6),
 (60, 'Camembert Pierrot', 4, 34, 7),
 (69, 'Gudbrandsdalsost', 4, 36, 8),
 (71, 'Flotemysost', 4, 21.5, 9),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 10),
 (22, "Gustaf's Knäckebröd", 5, 21, 1),
 (23, 'Tunnbröd', 5, 9, 2),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 3),
 (52, 'Filo Mix', 5, 7, 4),
 (56, 'Gnocchi di nonna Alice', 5, 38, 5),
 (57, 'Ravioli Angelo', 5, 19.5, 6),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 7),
 (9, 'Mishi Kobe Niku', 6, 97, 1),
 (17, 'Alice Mutton', 6, 39, 2),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 3),
 (53, 'Perth Pasties', 6, 32.8, 4),
 (54, 'Tourtière', 6, 7.45, 5),
 (55, 'Pâté chinois', 6, 24, 6),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 1),
 (14, 'Tofu', 7, 23.25, 2),
 (28, 'Rössle Sauerkraut', 7, 45.6, 3),
 (51, 'Manjimup Dried Apples', 7, 53, 4),
 (74, 'Longlife Tofu', 7, 10, 5),
 (10, 'Ikura', 8, 31, 1),
 (13, 'Konbu', 8, 6, 2),
 (18, 'Carnarvon Tigers', 8, 62.5, 3),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 4),
 (36, 'Inlagd Sill', 8, 19, 5),
 (37, 'Gravad lax', 8, 26, 6),
 (40, 'Boston Crab Meat', 8, 18.4, 7),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 8),
 (45, 'Rogede sild', 8, 9.5, 9),
 (46, 'Spegesild', 8, 12, 10),
 (58, 'Escargots de Bourgogne', 8, 13.25, 11),
 (73, 'Röd Kaviar', 8, 15, 12)]

GROUP BY Equivalent

❌ Like cumulative sums, running counts cannot be done with plain GROUP BY.
We can use correlated subquery:

In [35]:
%%sql
SELECT 
    p1.ProductID,
    p1.ProductName,
    p1.CategoryID,
    p1.Price,
    (
        SELECT COUNT(*)
        FROM Products p2
        WHERE p2.CategoryID = p1.CategoryID
          AND p2.ProductID <= p1.ProductID
    ) AS running_product_count
FROM Products p1
ORDER BY p1.CategoryID, p1.ProductID;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 18, 1),
 (2, 'Chang', 1, 19, 2),
 (24, 'Guaraná Fantástica', 1, 4.5, 3),
 (34, 'Sasquatch Ale', 1, 14, 4),
 (35, 'Steeleye Stout', 1, 18, 5),
 (38, 'Côte de Blaye', 1, 263.5, 6),
 (39, 'Chartreuse verte', 1, 18, 7),
 (43, 'Ipoh Coffee', 1, 46, 8),
 (67, 'Laughing Lumberjack Lager', 1, 14, 9),
 (70, 'Outback Lager', 1, 15, 10),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 11),
 (76, 'Lakkalikööri', 1, 18, 12),
 (3, 'Aniseed Syrup', 2, 10, 1),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 2),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 3),
 (6, "Grandma's Boysenberry Spread", 2, 25, 4),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 5),
 (15, 'Genen Shouyu', 2, 15.5, 6),
 (44, 'Gula Malacca', 2, 19.45, 7),
 (61, "Sirop d'érable", 2, 28.5, 8),
 (63, 'Vegie-spread', 2, 43.9, 9),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 10),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 11),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 12),
 (16, 'Pavlova', 3, 17.45, 1),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 2),
 (20, "Sir Rodney's Marmalade", 3, 81, 3),
 (21, "Sir Rodney's Scones", 3, 10, 4),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 5),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 6),
 (27, 'Schoggi Schokolade', 3, 43.9, 7),
 (47, 'Zaanse koeken', 3, 9.5, 8),
 (48, 'Chocolade', 3, 12.75, 9),
 (49, 'Maxilaku', 3, 20, 10),
 (50, 'Valkoinen suklaa', 3, 16.25, 11),
 (62, 'Tarte au sucre', 3, 49.3, 12),
 (68, 'Scottish Longbreads', 3, 12.5, 13),
 (11, 'Queso Cabrales', 4, 21, 1),
 (12, 'Queso Manchego La Pastora', 4, 38, 2),
 (31, 'Gorgonzola Telino', 4, 12.5, 3),
 (32, 'Mascarpone Fabioli', 4, 32, 4),
 (33, 'Geitost', 4, 2.5, 5),
 (59, 'Raclette Courdavault', 4, 55, 6),
 (60, 'Camembert Pierrot', 4, 34, 7),
 (69, 'Gudbrandsdalsost', 4, 36, 8),
 (71, 'Flotemysost', 4, 21.5, 9),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 10),
 (22, "Gustaf's Knäckebröd", 5, 21, 1),
 (23, 'Tunnbröd', 5, 9, 2),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 3),
 (52, 'Filo Mix', 5, 7, 4),
 (56, 'Gnocchi di nonna Alice', 5, 38, 5),
 (57, 'Ravioli Angelo', 5, 19.5, 6),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 7),
 (9, 'Mishi Kobe Niku', 6, 97, 1),
 (17, 'Alice Mutton', 6, 39, 2),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 3),
 (53, 'Perth Pasties', 6, 32.8, 4),
 (54, 'Tourtière', 6, 7.45, 5),
 (55, 'Pâté chinois', 6, 24, 6),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 1),
 (14, 'Tofu', 7, 23.25, 2),
 (28, 'Rössle Sauerkraut', 7, 45.6, 3),
 (51, 'Manjimup Dried Apples', 7, 53, 4),
 (74, 'Longlife Tofu', 7, 10, 5),
 (10, 'Ikura', 8, 31, 1),
 (13, 'Konbu', 8, 6, 2),
 (18, 'Carnarvon Tigers', 8, 62.5, 3),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 4),
 (36, 'Inlagd Sill', 8, 19, 5),
 (37, 'Gravad lax', 8, 26, 6),
 (40, 'Boston Crab Meat', 8, 18.4, 7),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 8),
 (45, 'Rogede sild', 8, 9.5, 9),
 (46, 'Spegesild', 8, 12, 10),
 (58, 'Escargots de Bourgogne', 8, 13.25, 11),
 (73, 'Röd Kaviar', 8, 15, 12)]

# Count the number of customers per country

In [6]:
%%sql

SELECT 

Country, 

COUNT(*) AS Total_Customers

FROM Customers

GROUP BY Country;

 * sqlite:///northwind1.db
Done.

[(None, 3),
 ('Argentina', 3),
 ('Austria', 2),
 ('Belgium', 2),
 ('Brazil', 9),
 ('Canada', 3),
 ('Denmark', 2),
 ('Finland', 2),
 ('France', 11),
 ('Germany', 11),
 ('Ireland', 1),
 ('Italy', 3),
 ('Mexico', 5),
 ('Norway', 1),
 ('Poland', 1),
 ('Portugal', 2),
 ('Spain', 5),
 ('Sweden', 2),
 ('Switzerland', 2),
 ('UK', 7),
 ('USA', 30),
 ('Venezuela', 4)]

In [8]:
%%sql

SELECT 

COUNT(*) AS Total_Customers

FROM Customers;

 * sqlite:///northwind1.db
Done.

[(111,)]

In [12]:
%%sql

SELECT 
Country, 
COUNT(*) AS Total_Customers
FROM Customers
GROUP BY Country
ORDER BY Total_Customers
desc;

 * sqlite:///northwind1.db
Done.

[('USA', 30),
 ('Germany', 11),
 ('France', 11),
 ('Brazil', 9),
 ('UK', 7),
 ('Spain', 5),
 ('Mexico', 5),
 ('Venezuela', 4),
 ('Italy', 3),
 ('Canada', 3),
 ('Argentina', 3),
 (None, 3),
 ('Switzerland', 2),
 ('Sweden', 2),
 ('Portugal', 2),
 ('Finland', 2),
 ('Denmark', 2),
 ('Belgium', 2),
 ('Austria', 2),
 ('Poland', 1),
 ('Norway', 1),
 ('Ireland', 1)]

# Get the average price of the product in each category

In [28]:
%%sql

SELECT *
FROM Products
Limit 5;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 1, '10 boxes x 20 bags', 18),
 (2, 'Chang', 1, 1, '24 - 12 oz bottles', 19),
 (3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10),
 (4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22),
 (5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35)]

In [29]:
%%sql

SELECT AVG(Price) AS AvgPrice 
FROM Products;

 * sqlite:///northwind1.db
Done.

[(28.866363636363637,)]

In [30]:
%%sql

SELECT AVG(Price) AS AvgPrice 
FROM Products
group by CategoryID;

 * sqlite:///northwind1.db
Done.

[(37.979166666666664,),
 (23.0625,),
 (25.16,),
 (28.73,),
 (20.25,),
 (54.00666666666667,),
 (32.37,),
 (20.6825,)]

In [21]:
%%sql

SELECT CategoryID, AVG(Price) AS AvgPrice 
FROM Products
group by CategoryID;

 * sqlite:///northwind1.db
Done.

[(1, 37.979166666666664),
 (2, 23.0625),
 (3, 25.16),
 (4, 28.73),
 (5, 20.25),
 (6, 54.00666666666667),
 (7, 32.37),
 (8, 20.6825)]

In [20]:
%%sql

select * FROM categories;

 * sqlite:///northwind1.db
Done.

[(1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (3, 'Confections', 'Desserts, candies, and sweet breads'),
 (4, 'Dairy Products', 'Cheeses'),
 (5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (6, 'Meat/Poultry', 'Prepared meats'),
 (7, 'Produce', 'Dried fruit and bean curd'),
 (8, 'Seafood', 'Seaweed and fish')]

In [22]:
%%sql

SELECT CategoryID, AVG(Price) AS AvgPrice 
FROM Products
group by CategoryID
order by AVG(Price);

 * sqlite:///northwind1.db
Done.

[(5, 20.25),
 (8, 20.6825),
 (2, 23.0625),
 (3, 25.16),
 (4, 28.73),
 (7, 32.37),
 (1, 37.979166666666664),
 (6, 54.00666666666667)]

In [23]:
%%sql

SELECT CategoryID, AVG(Price) AS AvgPrice 
FROM Products
group by CategoryID
order by AVG(Price);

 * sqlite:///northwind1.db
Done.

[(5, 20.25),
 (8, 20.6825),
 (2, 23.0625),
 (3, 25.16),
 (4, 28.73),
 (7, 32.37),
 (1, 37.979166666666664),
 (6, 54.00666666666667)]

## repeate same for sum of price within each category

# Get Minimum and Maxmium Price per Category

In [26]:
%%sql

SELECT CategoryID, 
MAX(Price) AS Max_Price, 
MIN(Price) AS Min_Price

FROM Products
GROUP BY CategoryID;

 * sqlite:///northwind1.db
Done.

[(1, 263.5, 4.5),
 (2, 43.9, 10),
 (3, 81, 9.2),
 (4, 55, 2.5),
 (5, 38, 7),
 (6, 123.79, 7.45),
 (7, 53, 10),
 (8, 62.5, 6)]

In [27]:
%%sql

select * FROM categories;

 * sqlite:///northwind1.db
Done.

[(1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (3, 'Confections', 'Desserts, candies, and sweet breads'),
 (4, 'Dairy Products', 'Cheeses'),
 (5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (6, 'Meat/Poultry', 'Prepared meats'),
 (7, 'Produce', 'Dried fruit and bean curd'),
 (8, 'Seafood', 'Seaweed and fish')]

In [24]:
%%sql

SELECT 
    c.CategoryName,
    p.CategoryID, 
    MAX(p.Price) AS Max_Price, 
    MIN(p.Price) AS Min_Price
FROM Products p
JOIN Categories c 
    ON p.CategoryID = c.CategoryID
GROUP BY 
    c.CategoryName, 
    p.CategoryID;

 * sqlite:///northwind1.db
Done.

[('Beverages', 1, 263.5, 4.5),
 ('Condiments', 2, 43.9, 10),
 ('Confections', 3, 81, 9.2),
 ('Dairy Products', 4, 55, 2.5),
 ('Grains/Cereals', 5, 38, 7),
 ('Meat/Poultry', 6, 123.79, 7.45),
 ('Produce', 7, 53, 10),
 ('Seafood', 8, 62.5, 6)]

In [32]:
%%sql

SELECT country,
city,
count(*) AS Total_customers_per_country_per_city
From Customers

group by country, city;

 * sqlite:///northwind1.db
Done.

[(None, 'Boston', 1),
 (None, 'Denver', 1),
 (None, 'Detroit', 1),
 ('Argentina', 'Buenos Aires', 3),
 ('Austria', 'Graz', 1),
 ('Austria', 'Salzburg', 1),
 ('Belgium', 'Bruxelles', 1),
 ('Belgium', 'Charleroi', 1),
 ('Brazil', 'Campinas', 1),
 ('Brazil', 'Resende', 1),
 ('Brazil', 'Rio de Janeiro', 3),
 ('Brazil', 'São Paulo', 4),
 ('Canada', 'Montréal', 1),
 ('Canada', 'Tsawassen', 1),
 ('Canada', 'Vancouver', 1),
 ('Denmark', 'København', 1),
 ('Denmark', 'Århus', 1),
 ('Finland', 'Helsinki', 1),
 ('Finland', 'Oulu', 1),
 ('France', 'Lille', 1),
 ('France', 'Lyon', 1),
 ('France', 'Marseille', 1),
 ('France', 'Nantes', 2),
 ('France', 'Paris', 2),
 ('France', 'Reims', 1),
 ('France', 'Strasbourg', 1),
 ('France', 'Toulouse', 1),
 ('France', 'Versailles', 1),
 ('Germany', 'Aachen', 1),
 ('Germany', 'Berlin', 1),
 ('Germany', 'Brandenburg', 1),
 ('Germany', 'Cunewalde', 1),
 ('Germany', 'Frankfurt a.M.', 1),
 ('Germany', 'Köln', 1),
 ('Germany', 'Leipzig', 1),
 ('Germany', 'Mannheim', 1),
 ('Germany', 'München', 1),
 ('Germany', 'Münster', 1),
 ('Germany', 'Stuttgart', 1),
 ('Ireland', 'Cork', 1),
 ('Italy', 'Bergamo', 1),
 ('Italy', 'Reggio Emilia', 1),
 ('Italy', 'Torino', 1),
 ('Mexico', 'México D.F.', 5),
 ('Norway', 'Stavern', 1),
 ('Poland', 'Walla', 1),
 ('Portugal', 'Lisboa', 2),
 ('Spain', 'Barcelona', 1),
 ('Spain', 'Madrid', 3),
 ('Spain', 'Sevilla', 1),
 ('Sweden', 'Bräcke', 1),
 ('Sweden', 'Luleå', 1),
 ('Switzerland', 'Bern', 1),
 ('Switzerland', 'Genève', 1),
 ('UK', 'Cowes', 1),
 ('UK', 'London', 6),
 ('USA', None, 3),
 ('USA', 'Albuquerque', 1),
 ('USA', 'Anchorage', 1),
 ('USA', 'Atlanta', 1),
 ('USA', 'Boise', 1),
 ('USA', 'Butte', 1),
 ('USA', 'Chicago', 1),
 ('USA', 'Dallas', 1),
 ('USA', 'Elgin', 1),
 ('USA', 'Eugene', 1),
 ('USA', 'Houston', 1),
 ('USA', 'Kirkland', 1),
 ('USA', 'Lander', 1),
 ('USA', 'Las Vegas', 1),
 ('USA', 'Los Angeles', 1),
 ('USA', 'Miami', 1),
 ('USA', 'New York', 1),
 ('USA', 'Orlando', 1),
 ('USA', 'Phoenix', 1),
 ('USA', 'Portland', 3),
 ('USA', 'San Diego', 1),
 ('USA', 'San Francisco', 2),
 ('USA', 'Seattle', 2),
 ('USA', 'Walla Walla', 1),
 ('Venezuela', 'Barquisimeto', 1),
 ('Venezuela', 'Caracas', 1),
 ('Venezuela', 'I. de Margarita', 1),
 ('Venezuela', 'San Cristóbal', 1)]

In [45]:
%%sql

SELECT country, city, count(*) AS total_cust

From Customers

group by country, city

having count(*) > 2

order by count(*) asc;

 * sqlite:///northwind1.db
Done.

[('Argentina', 'Buenos Aires', 3),
 ('Brazil', 'Rio de Janeiro', 3),
 ('Spain', 'Madrid', 3),
 ('USA', None, 3),
 ('USA', 'Portland', 3),
 ('Brazil', 'São Paulo', 4),
 ('Mexico', 'México D.F.', 5),
 ('UK', 'London', 6)]

# 🚨 Common Mistakes
## ❌ Using columns in SELECT that are not in GROUP BY or aggregate functions.

## ❌ Using WHERE instead of HAVING for aggregated values.

# ✅ Best Practices

### Always use aggregate functions with columns not in the GROUP BY clause.

### Use HAVING to filter aggregated results.

### Use aliases to improve readability of output.

In [ ]:
%%sql

SELECT * 
FROM Suppliers
Limit 5;

# Get all suppliers and customers from London. (Using Multiple CTEs)

In [ ]:
%%sql

WITH LondonCustomers AS (
    SELECT CustomerID, ContactName, City FROM Customers WHERE City = 'London'
),
LondonSuppliers AS (
    SELECT SupplierID, ContactName, City FROM  WHERE City =Suppliers 'London'
)
SELECT * FROM LondonCustomers
UNION ALL
SELECT * FROM LondonSuppliers;

In [ ]:
%%sql

WITH LondonCustomers AS (
    SELECT 
        CustomerID AS ID, 
        ContactName, 
        City, 
        'Customer' AS Type
    FROM Customers 
    WHERE City = 'London'
),
LondonSuppliers AS (
    SELECT 
        SupplierID AS ID, 
        ContactName, 
        City, 
        'Supplier' AS Type
    FROM Suppliers 
    WHERE City = 'London'
)
SELECT * FROM LondonCustomers
UNION ALL
SELECT * FROM LondonSuppliers;

In [ ]:
%%sql

SELECT * FROM Products
Limit 10;

In [ ]:
%%sql

WITH AvgPriceCTE AS (
    SELECT AVG(Price) AS AvgPrice FROM Products
)
SELECT *
FROM Products
WHERE Price > (SELECT AvgPrice FROM AvgPriceCTE);

# 📌 This gives you the number of products in each category.

In [ ]:
%%sql

WITH CategoryCounts AS (
    SELECT CategoryID, COUNT(*) AS TotalProducts
    FROM Products
    GROUP BY CategoryID
)
SELECT *
FROM CategoryCounts;

# CTE to Identify Duplicate Prices
📌 Finds all products that share the same price as others (duplicates).

In [ ]:
%%sql

WITH PriceCounts AS (
    SELECT Price, COUNT(*) AS Occurrences
    FROM Products
    GROUP BY Price
    HAVING COUNT(*) > 1
)
SELECT *
FROM Products
WHERE Price IN (SELECT Price FROM PriceCounts) order by price;

# CTE to Get the Cheapest Product Per Category

In [ ]:
%%sql

SELECT CategoryID, MIN(Price) AS MinPrice
    FROM Products
    GROUP BY CategoryID;

In [ ]:
%%sql

WITH MinPrices AS (
    SELECT CategoryID, MIN(Price) AS MinPrice
    FROM Products
    GROUP BY CategoryID
)
SELECT *
FROM Products
WHERE (CategoryID, Price) IN (
    SELECT CategoryID, MinPrice FROM MinPrices
) order by CategoryID;

# Get the employees who handle more than 2 territories.

In [ ]:
%%sql

WITH TerritoryCount AS (
    SELECT EmployeeID, COUNT(*) AS TotalTerritories
    FROM EmployeeTerritories
    GROUP BY EmployeeID
)
SELECT E.FirstName, E.LastName, T.TotalTerritories
FROM Employees E
JOIN TerritoryCount T ON E.EmployeeID = T.EmployeeID
WHERE T.TotalTerritories > 2;

# 📌 Returns the most expensive product in each category.

In [ ]:
%%sql

WITH RankedCategory AS (
    SELECT ProductID, ProductName, CategoryID, Price,
           RANK() OVER (PARTITION BY CategoryID ORDER BY Price DESC) AS RankInCategory
    FROM Products
)
SELECT *
FROM RankedCategory
WHERE RankInCategory = 1;

# 📌 Filters category 3 products, then returns the top 3 most expensive among them.

In [ ]:
%%sql

WITH Filtered AS (
    SELECT * FROM Products WHERE CategoryID = 3
),
Ranked AS (
    SELECT ProductID, ProductName, Price,
           DENSE_RANK() OVER (ORDER BY Price DESC) AS PriceRank
    FROM Filtered
)
SELECT * FROM Ranked WHERE PriceRank <= 3;

In [ ]:
%%sql

SELECT * FROM Products
ORDER BY ProductName;

# 📌 Categorizes products into 'Low', 'Medium', and 'High' price brackets.

In [ ]:
%%sql

WITH PriceBuckets AS (
    SELECT ProductID, ProductName, Price,
           CASE 
               WHEN Price < 10 THEN 'Low'
               WHEN Price BETWEEN 10 AND 30 THEN 'Medium'
               ELSE 'High'
           END AS PriceCategory
    FROM Products
)
SELECT *
FROM PriceBuckets
WHERE PriceCategory = 'Low';

# Recursive CTEs

In [ ]:
%%sql

WITH RECURSIVE FactorialCTE(n, fact) AS (
    SELECT 1, 1
    UNION ALL
    SELECT n + 1, (n + 1) * fact
    FROM FactorialCTE
    WHERE n < 5
)
SELECT * FROM FactorialCTE;

# Return all customers that starts with "E" and are at least 3 characters in length

In [ ]:
%%sql

SELECT * FROM Customers
WHERE CustomerName LIKE 'E__%';

# END..... Practice Below...

In [ ]:
%%sql

SELECT * 
FROM Customers
WHERE country = 'Brazil';

In [ ]:
%%sql

SELECT * 
FROM Customers
WHERE CustomerID=3;

In [ ]:
%%sql

SELECT * FROM Products;

In [ ]:
%%sql

SELECT *
FROM Products
WHERE Price > 40;

In [ ]:
%%sql

SELECT * 
FROM Products
WHERE Price < 40;

In [ ]:
%%sql

SELECT * 
FROM Products
WHERE Price >= 30;

In [ ]:
%%sql

SELECT * 
FROM Products
WHERE Price <= 30;

In [ ]:
%%sql

SELECT * FROM Products
WHERE Price <> 30;

In [ ]:
%%sql

SELECT * 
FROM Products
WHERE Price BETWEEN 30 AND 40;

In [ ]:
%%sql

SELECT * 
FROM Customers
WHERE City IN ('Paris','London');

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql