In [1]:
# Install ipython-sql if not already installed
# !pip install ipython-sql

In [2]:
import sqlite3
import sql
import pandas as pd
import numpy as np

# Connect to a database (creates the database file if it doesn't exist)
cnn = sqlite3.connect('northwind1.db')

In [3]:
import sql

# Load the SQL extension
%load_ext sql

# Connect to a SQLite database
%sql sqlite:///northwind1.db

#display style of SQL query results in Jupyter Notebook
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [4]:
%%sql

SELECT name FROM sqlite_master WHERE type='table';

 * sqlite:///northwind1.db
Done.

[('sqlite_sequence',),
 ('CustomerCustomerDemo',),
 ('CustomerDemographics',),
 ('EmployeeTerritories',),
 ('Regions',),
 ('Territories',),
 ('Categories',),
 ('Orders',),
 ('Products',),
 ('Shippers',),
 ('Suppliers',),
 ('Employees',),
 ('Customers_new',),
 ('Customers',),
 ('Monthly_Sales',)]

In [4]:
from sqlalchemy import create_engine
import pandas as pd

# Connect to the SQLite database
engine = create_engine("sqlite:///northwind1.db")

# List of all tables
tables = [
     "EmployeeTerritories", "Regions", "Territories",
    "Categories", "Orders", "Products", "Shippers", "Suppliers", "Employees", "Customers"
]

# Loop through each table and display top 2 rows
for table in tables:
    print(f"\n--- {table} ---")
    df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 5;", engine)
    display(df)  # use display() in Jupyter to format nicely

--- EmployeeTerritories ---

   EmployeeID TerritoryID
0           1       06897
1           1       19713
2           2       01581
3           2       01730
4           2       01833

--- Regions ---

   RegionID RegionDescription
0         1           Eastern
1         2           Western
2         3          Northern
3         4          Southern

--- Territories ---

  TerritoryID TerritoryDescription  RegionID
0       01581             Westboro         1
1       01730              Bedford         1
2       01833            Georgetow         1
3       02116               Boston         1
4       02139            Cambridge         1

--- Categories ---

,CategoryID,CategoryName,Description
0,1,Beverages,"Soft drinks, coffees, teas, beers, and ales"
1,2,Condiments,"Sweet and savory sauces, relishes, spreads, an..."
2,3,Confections,"Desserts, candies, and sweet breads"
3,4,Dairy Products,Cheeses
4,5,Grains/Cereals,"Breads, crackers, pasta, and cereal"

--- Orders ---

   OrderID CustomerID  EmployeeID   OrderDate  ShipperID
0    10248      VINET           5  2016-07-04          3
1    10249      TOMSP           6  2016-07-05          1
2    10250      HANAR           4  2016-07-08          2
3    10251      VICTE           3  2016-07-08          1
4    10252      SUPRD           4  2016-07-09          2

--- Products ---

,ProductID,ProductName,SupplierID,CategoryID,Unit,Price
0,1,Chai,1,1,10 boxes x 20 bags,18.00
1,2,Chang,1,1,24 - 12 oz bottles,19.00
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35

--- Shippers ---

   ShipperID       ShipperName           Phone
0          1    Speedy Express  (503) 555-9831
1          2    United Package  (503) 555-3199
2          3  Federal Shipping  (503) 555-9931

--- Suppliers ---

,SupplierID,SupplierName,ContactName,Address,City,PostalCode,Country,Phone
0,1,Exotic Liquids,Charlotte Cooper,49 Gilbert St.,London,EC1 4SD,UK,(171) 555-2222
1,2,New Orleans Cajun Delights,Shelley Burke,P.O. Box 78934,New Orleans,70117,USA,(100) 555-4822
2,3,Grandma Kelly's Homestead,Regina Murphy,707 Oxford Rd.,Ann Arbor,48104,USA,(313) 555-5735
3,4,Tokyo Traders,Yoshi Nagase,9-8 Sekimai\nMusashino-shi,Tokyo,100,Japan,(03) 3555-5011
4,5,Cooperativa de Quesos 'Las Cabras',Antonio del Valle Saavedra,Calle del Rosal 4,Oviedo,33007,Spain,(98) 598 76 54

--- Employees ---

,EmployeeID,LastName,FirstName,BirthDate,Notes
0,1,Davolio,Nancy,1968-12-08,Education includes a BA in psychology from Col...
1,2,Fuller,Andrew,1972-02-19,Andrew received his BTS commercial in 1974 and...
2,3,Leverling,Janet,1983-08-30,Janet has a BS degree in chemistry from Boston...
3,4,Peacock,Margaret,1957-09-19,Margaret holds a BA in English literature from...
4,5,Buchanan,Steven,1975-03-04,Steven Buchanan graduated from St. Andrews Uni...

--- Customers ---

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
0,1,Alfreds Futterkiste,Maria Anders,Obere Str. 57,Berlin,12209,Germany
1,2,Ana Trujillo Emparedados y helados,Ana Trujillo,Avda. de la Constitución 2222,México D.F.,05021,Mexico
2,3,Antonio Moreno Taquería,Antonio Moreno,Mataderos 2312,México D.F.,05023,Mexico
3,4,Around the Horn,Thomas Hardy,120 Hanover Sq.,London,WA1 1DP,UK
4,5,Berglunds snabbköp,Christina Berglund,Berguvsvägen 8,Luleå,S-958 22,Sweden

In [6]:
%%sql

SELECT * 
FROM Products;

 * sqlite:///northwind1.db
Done.

[(1, 'Chai', 1, 1, '10 boxes x 20 bags', 18),
 (2, 'Chang', 1, 1, '24 - 12 oz bottles', 19),
 (3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10),
 (4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22),
 (5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35),
 (6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25),
 (7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30),
 (8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40),
 (9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97),
 (10, 'Ikura', 4, 8, '12 - 200 ml jars', 31),
 (11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21),
 (12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38),
 (13, 'Konbu', 6, 8, '2 kg box', 6),
 (14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23.25),
 (15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5),
 (16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17.45),
 (17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39),
 (18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5),
 (19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 9.2),
 (20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81),
 (21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10),
 (22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21),
 (23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9),
 (24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 4.5),
 (25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14),
 (26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23),
 (27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9),
 (28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6),
 (29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79),
 (30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25.89),
 (31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 12.5),
 (32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32),
 (33, 'Geitost', 15, 4, '500 g', 2.5),
 (34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14),
 (35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18),
 (36, 'Inlagd Sill', 17, 8, '24 - 250 g  jars', 19),
 (37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26),
 (38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5),
 (39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18),
 (40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 18.4),
 (41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 9.65),
 (42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14),
 (43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46),
 (44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45),
 (45, 'Rogede sild', 21, 8, '1k pkg.', 9.5),
 (46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12),
 (47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 9.5),
 (48, 'Chocolade', 22, 3, '10 pkgs.', 12.75),
 (49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20),
 (50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25),
 (51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53),
 (52, 'Filo Mix', 24, 5, '16 - 2 kg boxes', 7),
 (53, 'Perth Pasties', 24, 6, '48 pieces', 32.8),
 (54, 'Tourtière', 25, 6, '16 pies', 7.45),
 (55, 'Pâté chinois', 25, 6, '24 boxes x 2 pies', 24),
 (56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38),
 (57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 19.5),
 (58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13.25),
 (59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55),
 (60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34),
 (61, "Sirop d'érable", 29, 2, '24 - 500 ml bottles', 28.5),
 (62, 'Tarte au sucre', 29, 3, '48 pies', 49.3),
 (63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43.9),
 (64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 21.05),
 (66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17),
 (67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14),
 (68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5),
 (69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36),
 (70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15),
 (71, 'Flotemysost', 15, 4, '10 - 500 g pkgs.', 21.5),
 (72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8),
 (73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15),
 (74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10),
 (75, 'Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 7.75),
 (76, 'Lakkalikööri', 23, 1, '500 ml', 18),
 (77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13)]

# 1️⃣ ROW_NUMBER()

In [7]:
%%sql

-- 👉 Assigns a unique row number to All products, ordered by price descending.


SELECT ProductID, ProductName, CategoryID, Price,
       ROW_NUMBER() OVER (ORDER BY Price DESC) AS RowNum
FROM Products;

 * sqlite:///northwind1.db
Done.

[(38, 'Côte de Blaye', 1, 263.5, 1),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 2),
 (9, 'Mishi Kobe Niku', 6, 97, 3),
 (20, "Sir Rodney's Marmalade", 3, 81, 4),
 (18, 'Carnarvon Tigers', 8, 62.5, 5),
 (59, 'Raclette Courdavault', 4, 55, 6),
 (51, 'Manjimup Dried Apples', 7, 53, 7),
 (62, 'Tarte au sucre', 3, 49.3, 8),
 (43, 'Ipoh Coffee', 1, 46, 9),
 (28, 'Rössle Sauerkraut', 7, 45.6, 10),
 (27, 'Schoggi Schokolade', 3, 43.9, 11),
 (63, 'Vegie-spread', 2, 43.9, 12),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 13),
 (17, 'Alice Mutton', 6, 39, 14),
 (12, 'Queso Manchego La Pastora', 4, 38, 15),
 (56, 'Gnocchi di nonna Alice', 5, 38, 16),
 (69, 'Gudbrandsdalsost', 4, 36, 17),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 18),
 (60, 'Camembert Pierrot', 4, 34, 19),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 20),
 (53, 'Perth Pasties', 6, 32.8, 21),
 (32, 'Mascarpone Fabioli', 4, 32, 22),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 23),
 (10, 'Ikura', 8, 31, 24),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 25),
 (61, "Sirop d'érable", 2, 28.5, 26),
 (37, 'Gravad lax', 8, 26, 27),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 28),
 (6, "Grandma's Boysenberry Spread", 2, 25, 29),
 (55, 'Pâté chinois', 6, 24, 30),
 (14, 'Tofu', 7, 23.25, 31),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 32),
 (71, 'Flotemysost', 4, 21.5, 33),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 34),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 35),
 (11, 'Queso Cabrales', 4, 21, 36),
 (22, "Gustaf's Knäckebröd", 5, 21, 37),
 (49, 'Maxilaku', 3, 20, 38),
 (57, 'Ravioli Angelo', 5, 19.5, 39),
 (44, 'Gula Malacca', 2, 19.45, 40),
 (2, 'Chang', 1, 19, 41),
 (36, 'Inlagd Sill', 8, 19, 42),
 (40, 'Boston Crab Meat', 8, 18.4, 43),
 (1, 'Chai', 1, 18, 44),
 (35, 'Steeleye Stout', 1, 18, 45),
 (39, 'Chartreuse verte', 1, 18, 46),
 (76, 'Lakkalikööri', 1, 18, 47),
 (16, 'Pavlova', 3, 17.45, 48),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 49),
 (50, 'Valkoinen suklaa', 3, 16.25, 50),
 (15, 'Genen Shouyu', 2, 15.5, 51),
 (70, 'Outback Lager', 1, 15, 52),
 (73, 'Röd Kaviar', 8, 15, 53),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 54),
 (34, 'Sasquatch Ale', 1, 14, 55),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 56),
 (67, 'Laughing Lumberjack Lager', 1, 14, 57),
 (58, 'Escargots de Bourgogne', 8, 13.25, 58),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 59),
 (48, 'Chocolade', 3, 12.75, 60),
 (31, 'Gorgonzola Telino', 4, 12.5, 61),
 (68, 'Scottish Longbreads', 3, 12.5, 62),
 (46, 'Spegesild', 8, 12, 63),
 (3, 'Aniseed Syrup', 2, 10, 64),
 (21, "Sir Rodney's Scones", 3, 10, 65),
 (74, 'Longlife Tofu', 7, 10, 66),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 67),
 (45, 'Rogede sild', 8, 9.5, 68),
 (47, 'Zaanse koeken', 3, 9.5, 69),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 70),
 (23, 'Tunnbröd', 5, 9, 71),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 72),
 (54, 'Tourtière', 6, 7.45, 73),
 (52, 'Filo Mix', 5, 7, 74),
 (13, 'Konbu', 8, 6, 75),
 (24, 'Guaraná Fantástica', 1, 4.5, 76),
 (33, 'Geitost', 4, 2.5, 77)]

In [5]:
%%sql

-- 👉 Gives each product a unique sequential number within its category

SELECT ProductID, ProductName, CategoryID, Price,
       ROW_NUMBER() OVER (PARTITION BY CategoryID ORDER BY Price DESC) AS RowNum
FROM Products;

 * sqlite:///northwind1.db
Done.

[(38, 'Côte de Blaye', 1, 263.5, 1),
 (43, 'Ipoh Coffee', 1, 46, 2),
 (2, 'Chang', 1, 19, 3),
 (1, 'Chai', 1, 18, 4),
 (35, 'Steeleye Stout', 1, 18, 5),
 (39, 'Chartreuse verte', 1, 18, 6),
 (76, 'Lakkalikööri', 1, 18, 7),
 (70, 'Outback Lager', 1, 15, 8),
 (34, 'Sasquatch Ale', 1, 14, 9),
 (67, 'Laughing Lumberjack Lager', 1, 14, 10),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 11),
 (24, 'Guaraná Fantástica', 1, 4.5, 12),
 (63, 'Vegie-spread', 2, 43.9, 1),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 2),
 (61, "Sirop d'érable", 2, 28.5, 3),
 (6, "Grandma's Boysenberry Spread", 2, 25, 4),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 5),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 6),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 7),
 (44, 'Gula Malacca', 2, 19.45, 8),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 9),
 (15, 'Genen Shouyu', 2, 15.5, 10),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 11),
 (3, 'Aniseed Syrup', 2, 10, 12),
 (20, "Sir Rodney's Marmalade", 3, 81, 1),
 (62, 'Tarte au sucre', 3, 49.3, 2),
 (27, 'Schoggi Schokolade', 3, 43.9, 3),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 4),
 (49, 'Maxilaku', 3, 20, 5),
 (16, 'Pavlova', 3, 17.45, 6),
 (50, 'Valkoinen suklaa', 3, 16.25, 7),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 8),
 (48, 'Chocolade', 3, 12.75, 9),
 (68, 'Scottish Longbreads', 3, 12.5, 10),
 (21, "Sir Rodney's Scones", 3, 10, 11),
 (47, 'Zaanse koeken', 3, 9.5, 12),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 13),
 (59, 'Raclette Courdavault', 4, 55, 1),
 (12, 'Queso Manchego La Pastora', 4, 38, 2),
 (69, 'Gudbrandsdalsost', 4, 36, 3),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 4),
 (60, 'Camembert Pierrot', 4, 34, 5),
 (32, 'Mascarpone Fabioli', 4, 32, 6),
 (71, 'Flotemysost', 4, 21.5, 7),
 (11, 'Queso Cabrales', 4, 21, 8),
 (31, 'Gorgonzola Telino', 4, 12.5, 9),
 (33, 'Geitost', 4, 2.5, 10),
 (56, 'Gnocchi di nonna Alice', 5, 38, 1),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 2),
 (22, "Gustaf's Knäckebröd", 5, 21, 3),
 (57, 'Ravioli Angelo', 5, 19.5, 4),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 5),
 (23, 'Tunnbröd', 5, 9, 6),
 (52, 'Filo Mix', 5, 7, 7),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 1),
 (9, 'Mishi Kobe Niku', 6, 97, 2),
 (17, 'Alice Mutton', 6, 39, 3),
 (53, 'Perth Pasties', 6, 32.8, 4),
 (55, 'Pâté chinois', 6, 24, 5),
 (54, 'Tourtière', 6, 7.45, 6),
 (51, 'Manjimup Dried Apples', 7, 53, 1),
 (28, 'Rössle Sauerkraut', 7, 45.6, 2),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 3),
 (14, 'Tofu', 7, 23.25, 4),
 (74, 'Longlife Tofu', 7, 10, 5),
 (18, 'Carnarvon Tigers', 8, 62.5, 1),
 (10, 'Ikura', 8, 31, 2),
 (37, 'Gravad lax', 8, 26, 3),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 4),
 (36, 'Inlagd Sill', 8, 19, 5),
 (40, 'Boston Crab Meat', 8, 18.4, 6),
 (73, 'Röd Kaviar', 8, 15, 7),
 (58, 'Escargots de Bourgogne', 8, 13.25, 8),
 (46, 'Spegesild', 8, 12, 9),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 10),
 (45, 'Rogede sild', 8, 9.5, 11),
 (13, 'Konbu', 8, 6, 12)]

# 2️⃣ RANK()

In [9]:
%%sql

-- 👉 Ranks All products across the entire table, same price = same rank, skips Next rank.


SELECT ProductID, ProductName, CategoryID, Price,
       RANK() OVER (ORDER BY Price DESC) AS RankVal
FROM Products;

 * sqlite:///northwind1.db
Done.

[(38, 'Côte de Blaye', 1, 263.5, 1),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 2),
 (9, 'Mishi Kobe Niku', 6, 97, 3),
 (20, "Sir Rodney's Marmalade", 3, 81, 4),
 (18, 'Carnarvon Tigers', 8, 62.5, 5),
 (59, 'Raclette Courdavault', 4, 55, 6),
 (51, 'Manjimup Dried Apples', 7, 53, 7),
 (62, 'Tarte au sucre', 3, 49.3, 8),
 (43, 'Ipoh Coffee', 1, 46, 9),
 (28, 'Rössle Sauerkraut', 7, 45.6, 10),
 (27, 'Schoggi Schokolade', 3, 43.9, 11),
 (63, 'Vegie-spread', 2, 43.9, 11),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 13),
 (17, 'Alice Mutton', 6, 39, 14),
 (12, 'Queso Manchego La Pastora', 4, 38, 15),
 (56, 'Gnocchi di nonna Alice', 5, 38, 15),
 (69, 'Gudbrandsdalsost', 4, 36, 17),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 18),
 (60, 'Camembert Pierrot', 4, 34, 19),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 20),
 (53, 'Perth Pasties', 6, 32.8, 21),
 (32, 'Mascarpone Fabioli', 4, 32, 22),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 23),
 (10, 'Ikura', 8, 31, 24),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 25),
 (61, "Sirop d'érable", 2, 28.5, 26),
 (37, 'Gravad lax', 8, 26, 27),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 28),
 (6, "Grandma's Boysenberry Spread", 2, 25, 29),
 (55, 'Pâté chinois', 6, 24, 30),
 (14, 'Tofu', 7, 23.25, 31),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 32),
 (71, 'Flotemysost', 4, 21.5, 33),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 34),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 35),
 (11, 'Queso Cabrales', 4, 21, 36),
 (22, "Gustaf's Knäckebröd", 5, 21, 36),
 (49, 'Maxilaku', 3, 20, 38),
 (57, 'Ravioli Angelo', 5, 19.5, 39),
 (44, 'Gula Malacca', 2, 19.45, 40),
 (2, 'Chang', 1, 19, 41),
 (36, 'Inlagd Sill', 8, 19, 41),
 (40, 'Boston Crab Meat', 8, 18.4, 43),
 (1, 'Chai', 1, 18, 44),
 (35, 'Steeleye Stout', 1, 18, 44),
 (39, 'Chartreuse verte', 1, 18, 44),
 (76, 'Lakkalikööri', 1, 18, 44),
 (16, 'Pavlova', 3, 17.45, 48),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 49),
 (50, 'Valkoinen suklaa', 3, 16.25, 50),
 (15, 'Genen Shouyu', 2, 15.5, 51),
 (70, 'Outback Lager', 1, 15, 52),
 (73, 'Röd Kaviar', 8, 15, 52),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 54),
 (34, 'Sasquatch Ale', 1, 14, 54),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 54),
 (67, 'Laughing Lumberjack Lager', 1, 14, 54),
 (58, 'Escargots de Bourgogne', 8, 13.25, 58),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 59),
 (48, 'Chocolade', 3, 12.75, 60),
 (31, 'Gorgonzola Telino', 4, 12.5, 61),
 (68, 'Scottish Longbreads', 3, 12.5, 61),
 (46, 'Spegesild', 8, 12, 63),
 (3, 'Aniseed Syrup', 2, 10, 64),
 (21, "Sir Rodney's Scones", 3, 10, 64),
 (74, 'Longlife Tofu', 7, 10, 64),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 67),
 (45, 'Rogede sild', 8, 9.5, 68),
 (47, 'Zaanse koeken', 3, 9.5, 68),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 70),
 (23, 'Tunnbröd', 5, 9, 71),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 72),
 (54, 'Tourtière', 6, 7.45, 73),
 (52, 'Filo Mix', 5, 7, 74),
 (13, 'Konbu', 8, 6, 75),
 (24, 'Guaraná Fantástica', 1, 4.5, 76),
 (33, 'Geitost', 4, 2.5, 77)]

In [10]:
%%sql

-- 👉 Products With the same price within a catagory get the same rank, but the Next rank IS skipped.


SELECT ProductID, ProductName, CategoryID, Price,
       RANK() OVER (PARTITION BY CategoryID ORDER BY Price DESC) AS RankVal
FROM Products;

 * sqlite:///northwind1.db
Done.

[(38, 'Côte de Blaye', 1, 263.5, 1),
 (43, 'Ipoh Coffee', 1, 46, 2),
 (2, 'Chang', 1, 19, 3),
 (1, 'Chai', 1, 18, 4),
 (35, 'Steeleye Stout', 1, 18, 4),
 (39, 'Chartreuse verte', 1, 18, 4),
 (76, 'Lakkalikööri', 1, 18, 4),
 (70, 'Outback Lager', 1, 15, 8),
 (34, 'Sasquatch Ale', 1, 14, 9),
 (67, 'Laughing Lumberjack Lager', 1, 14, 9),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 11),
 (24, 'Guaraná Fantástica', 1, 4.5, 12),
 (63, 'Vegie-spread', 2, 43.9, 1),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 2),
 (61, "Sirop d'érable", 2, 28.5, 3),
 (6, "Grandma's Boysenberry Spread", 2, 25, 4),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 5),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 6),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 7),
 (44, 'Gula Malacca', 2, 19.45, 8),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 9),
 (15, 'Genen Shouyu', 2, 15.5, 10),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 11),
 (3, 'Aniseed Syrup', 2, 10, 12),
 (20, "Sir Rodney's Marmalade", 3, 81, 1),
 (62, 'Tarte au sucre', 3, 49.3, 2),
 (27, 'Schoggi Schokolade', 3, 43.9, 3),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 4),
 (49, 'Maxilaku', 3, 20, 5),
 (16, 'Pavlova', 3, 17.45, 6),
 (50, 'Valkoinen suklaa', 3, 16.25, 7),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 8),
 (48, 'Chocolade', 3, 12.75, 9),
 (68, 'Scottish Longbreads', 3, 12.5, 10),
 (21, "Sir Rodney's Scones", 3, 10, 11),
 (47, 'Zaanse koeken', 3, 9.5, 12),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 13),
 (59, 'Raclette Courdavault', 4, 55, 1),
 (12, 'Queso Manchego La Pastora', 4, 38, 2),
 (69, 'Gudbrandsdalsost', 4, 36, 3),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 4),
 (60, 'Camembert Pierrot', 4, 34, 5),
 (32, 'Mascarpone Fabioli', 4, 32, 6),
 (71, 'Flotemysost', 4, 21.5, 7),
 (11, 'Queso Cabrales', 4, 21, 8),
 (31, 'Gorgonzola Telino', 4, 12.5, 9),
 (33, 'Geitost', 4, 2.5, 10),
 (56, 'Gnocchi di nonna Alice', 5, 38, 1),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 2),
 (22, "Gustaf's Knäckebröd", 5, 21, 3),
 (57, 'Ravioli Angelo', 5, 19.5, 4),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 5),
 (23, 'Tunnbröd', 5, 9, 6),
 (52, 'Filo Mix', 5, 7, 7),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 1),
 (9, 'Mishi Kobe Niku', 6, 97, 2),
 (17, 'Alice Mutton', 6, 39, 3),
 (53, 'Perth Pasties', 6, 32.8, 4),
 (55, 'Pâté chinois', 6, 24, 5),
 (54, 'Tourtière', 6, 7.45, 6),
 (51, 'Manjimup Dried Apples', 7, 53, 1),
 (28, 'Rössle Sauerkraut', 7, 45.6, 2),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 3),
 (14, 'Tofu', 7, 23.25, 4),
 (74, 'Longlife Tofu', 7, 10, 5),
 (18, 'Carnarvon Tigers', 8, 62.5, 1),
 (10, 'Ikura', 8, 31, 2),
 (37, 'Gravad lax', 8, 26, 3),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 4),
 (36, 'Inlagd Sill', 8, 19, 5),
 (40, 'Boston Crab Meat', 8, 18.4, 6),
 (73, 'Röd Kaviar', 8, 15, 7),
 (58, 'Escargots de Bourgogne', 8, 13.25, 8),
 (46, 'Spegesild', 8, 12, 9),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 10),
 (45, 'Rogede sild', 8, 9.5, 11),
 (13, 'Konbu', 8, 6, 12)]

#   3️⃣ DENSE_RANK()

In [11]:
%%sql

-- 👉 Same As RANK(), but doesn’t skip ranks


SELECT ProductID, ProductName, CategoryID, Price,
       DENSE_RANK() OVER (ORDER BY Price DESC) AS DenseRankVal
FROM Products;

 * sqlite:///northwind1.db
Done.

[(38, 'Côte de Blaye', 1, 263.5, 1),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 2),
 (9, 'Mishi Kobe Niku', 6, 97, 3),
 (20, "Sir Rodney's Marmalade", 3, 81, 4),
 (18, 'Carnarvon Tigers', 8, 62.5, 5),
 (59, 'Raclette Courdavault', 4, 55, 6),
 (51, 'Manjimup Dried Apples', 7, 53, 7),
 (62, 'Tarte au sucre', 3, 49.3, 8),
 (43, 'Ipoh Coffee', 1, 46, 9),
 (28, 'Rössle Sauerkraut', 7, 45.6, 10),
 (27, 'Schoggi Schokolade', 3, 43.9, 11),
 (63, 'Vegie-spread', 2, 43.9, 11),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 12),
 (17, 'Alice Mutton', 6, 39, 13),
 (12, 'Queso Manchego La Pastora', 4, 38, 14),
 (56, 'Gnocchi di nonna Alice', 5, 38, 14),
 (69, 'Gudbrandsdalsost', 4, 36, 15),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 16),
 (60, 'Camembert Pierrot', 4, 34, 17),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 18),
 (53, 'Perth Pasties', 6, 32.8, 19),
 (32, 'Mascarpone Fabioli', 4, 32, 20),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 21),
 (10, 'Ikura', 8, 31, 22),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 23),
 (61, "Sirop d'érable", 2, 28.5, 24),
 (37, 'Gravad lax', 8, 26, 25),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 26),
 (6, "Grandma's Boysenberry Spread", 2, 25, 27),
 (55, 'Pâté chinois', 6, 24, 28),
 (14, 'Tofu', 7, 23.25, 29),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 30),
 (71, 'Flotemysost', 4, 21.5, 31),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 32),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 33),
 (11, 'Queso Cabrales', 4, 21, 34),
 (22, "Gustaf's Knäckebröd", 5, 21, 34),
 (49, 'Maxilaku', 3, 20, 35),
 (57, 'Ravioli Angelo', 5, 19.5, 36),
 (44, 'Gula Malacca', 2, 19.45, 37),
 (2, 'Chang', 1, 19, 38),
 (36, 'Inlagd Sill', 8, 19, 38),
 (40, 'Boston Crab Meat', 8, 18.4, 39),
 (1, 'Chai', 1, 18, 40),
 (35, 'Steeleye Stout', 1, 18, 40),
 (39, 'Chartreuse verte', 1, 18, 40),
 (76, 'Lakkalikööri', 1, 18, 40),
 (16, 'Pavlova', 3, 17.45, 41),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 42),
 (50, 'Valkoinen suklaa', 3, 16.25, 43),
 (15, 'Genen Shouyu', 2, 15.5, 44),
 (70, 'Outback Lager', 1, 15, 45),
 (73, 'Röd Kaviar', 8, 15, 45),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 46),
 (34, 'Sasquatch Ale', 1, 14, 46),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 46),
 (67, 'Laughing Lumberjack Lager', 1, 14, 46),
 (58, 'Escargots de Bourgogne', 8, 13.25, 47),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 48),
 (48, 'Chocolade', 3, 12.75, 49),
 (31, 'Gorgonzola Telino', 4, 12.5, 50),
 (68, 'Scottish Longbreads', 3, 12.5, 50),
 (46, 'Spegesild', 8, 12, 51),
 (3, 'Aniseed Syrup', 2, 10, 52),
 (21, "Sir Rodney's Scones", 3, 10, 52),
 (74, 'Longlife Tofu', 7, 10, 52),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 53),
 (45, 'Rogede sild', 8, 9.5, 54),
 (47, 'Zaanse koeken', 3, 9.5, 54),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 55),
 (23, 'Tunnbröd', 5, 9, 56),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 57),
 (54, 'Tourtière', 6, 7.45, 58),
 (52, 'Filo Mix', 5, 7, 59),
 (13, 'Konbu', 8, 6, 60),
 (24, 'Guaraná Fantástica', 1, 4.5, 61),
 (33, 'Geitost', 4, 2.5, 62)]

In [12]:
%%sql

-- 👉 Products With the same price get the same rank, And no rank Is skipped


SELECT ProductID, ProductName, CategoryID, Price,
       DENSE_RANK() OVER (PARTITION BY CategoryID ORDER BY Price DESC) AS DenseRankVal
FROM Products;

 * sqlite:///northwind1.db
Done.

[(38, 'Côte de Blaye', 1, 263.5, 1),
 (43, 'Ipoh Coffee', 1, 46, 2),
 (2, 'Chang', 1, 19, 3),
 (1, 'Chai', 1, 18, 4),
 (35, 'Steeleye Stout', 1, 18, 4),
 (39, 'Chartreuse verte', 1, 18, 4),
 (76, 'Lakkalikööri', 1, 18, 4),
 (70, 'Outback Lager', 1, 15, 5),
 (34, 'Sasquatch Ale', 1, 14, 6),
 (67, 'Laughing Lumberjack Lager', 1, 14, 6),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 7),
 (24, 'Guaraná Fantástica', 1, 4.5, 8),
 (63, 'Vegie-spread', 2, 43.9, 1),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 2),
 (61, "Sirop d'érable", 2, 28.5, 3),
 (6, "Grandma's Boysenberry Spread", 2, 25, 4),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 5),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 6),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 7),
 (44, 'Gula Malacca', 2, 19.45, 8),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 9),
 (15, 'Genen Shouyu', 2, 15.5, 10),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 11),
 (3, 'Aniseed Syrup', 2, 10, 12),
 (20, "Sir Rodney's Marmalade", 3, 81, 1),
 (62, 'Tarte au sucre', 3, 49.3, 2),
 (27, 'Schoggi Schokolade', 3, 43.9, 3),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 4),
 (49, 'Maxilaku', 3, 20, 5),
 (16, 'Pavlova', 3, 17.45, 6),
 (50, 'Valkoinen suklaa', 3, 16.25, 7),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 8),
 (48, 'Chocolade', 3, 12.75, 9),
 (68, 'Scottish Longbreads', 3, 12.5, 10),
 (21, "Sir Rodney's Scones", 3, 10, 11),
 (47, 'Zaanse koeken', 3, 9.5, 12),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 13),
 (59, 'Raclette Courdavault', 4, 55, 1),
 (12, 'Queso Manchego La Pastora', 4, 38, 2),
 (69, 'Gudbrandsdalsost', 4, 36, 3),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 4),
 (60, 'Camembert Pierrot', 4, 34, 5),
 (32, 'Mascarpone Fabioli', 4, 32, 6),
 (71, 'Flotemysost', 4, 21.5, 7),
 (11, 'Queso Cabrales', 4, 21, 8),
 (31, 'Gorgonzola Telino', 4, 12.5, 9),
 (33, 'Geitost', 4, 2.5, 10),
 (56, 'Gnocchi di nonna Alice', 5, 38, 1),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 2),
 (22, "Gustaf's Knäckebröd", 5, 21, 3),
 (57, 'Ravioli Angelo', 5, 19.5, 4),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 5),
 (23, 'Tunnbröd', 5, 9, 6),
 (52, 'Filo Mix', 5, 7, 7),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 1),
 (9, 'Mishi Kobe Niku', 6, 97, 2),
 (17, 'Alice Mutton', 6, 39, 3),
 (53, 'Perth Pasties', 6, 32.8, 4),
 (55, 'Pâté chinois', 6, 24, 5),
 (54, 'Tourtière', 6, 7.45, 6),
 (51, 'Manjimup Dried Apples', 7, 53, 1),
 (28, 'Rössle Sauerkraut', 7, 45.6, 2),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 3),
 (14, 'Tofu', 7, 23.25, 4),
 (74, 'Longlife Tofu', 7, 10, 5),
 (18, 'Carnarvon Tigers', 8, 62.5, 1),
 (10, 'Ikura', 8, 31, 2),
 (37, 'Gravad lax', 8, 26, 3),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 4),
 (36, 'Inlagd Sill', 8, 19, 5),
 (40, 'Boston Crab Meat', 8, 18.4, 6),
 (73, 'Röd Kaviar', 8, 15, 7),
 (58, 'Escargots de Bourgogne', 8, 13.25, 8),
 (46, 'Spegesild', 8, 12, 9),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 10),
 (45, 'Rogede sild', 8, 9.5, 11),
 (13, 'Konbu', 8, 6, 12)]

# 4️⃣ NTILE(n)

In [8]:
%%sql

-- 👉 Divides All products into 4 groups based on price ordering.


SELECT ProductID, ProductName, CategoryID, Price,
       NTILE(4) OVER (ORDER BY Price DESC) AS PriceGroup
FROM Products;

 * sqlite:///northwind1.db
Done.

[(38, 'Côte de Blaye', 1, 263.5, 1),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 1),
 (9, 'Mishi Kobe Niku', 6, 97, 1),
 (20, "Sir Rodney's Marmalade", 3, 81, 1),
 (18, 'Carnarvon Tigers', 8, 62.5, 1),
 (59, 'Raclette Courdavault', 4, 55, 1),
 (51, 'Manjimup Dried Apples', 7, 53, 1),
 (62, 'Tarte au sucre', 3, 49.3, 1),
 (43, 'Ipoh Coffee', 1, 46, 1),
 (28, 'Rössle Sauerkraut', 7, 45.6, 1),
 (27, 'Schoggi Schokolade', 3, 43.9, 1),
 (63, 'Vegie-spread', 2, 43.9, 1),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 1),
 (17, 'Alice Mutton', 6, 39, 1),
 (12, 'Queso Manchego La Pastora', 4, 38, 1),
 (56, 'Gnocchi di nonna Alice', 5, 38, 1),
 (69, 'Gudbrandsdalsost', 4, 36, 1),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 1),
 (60, 'Camembert Pierrot', 4, 34, 1),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 1),
 (53, 'Perth Pasties', 6, 32.8, 2),
 (32, 'Mascarpone Fabioli', 4, 32, 2),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 2),
 (10, 'Ikura', 8, 31, 2),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 2),
 (61, "Sirop d'érable", 2, 28.5, 2),
 (37, 'Gravad lax', 8, 26, 2),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 2),
 (6, "Grandma's Boysenberry Spread", 2, 25, 2),
 (55, 'Pâté chinois', 6, 24, 2),
 (14, 'Tofu', 7, 23.25, 2),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 2),
 (71, 'Flotemysost', 4, 21.5, 2),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 2),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 2),
 (11, 'Queso Cabrales', 4, 21, 2),
 (22, "Gustaf's Knäckebröd", 5, 21, 2),
 (49, 'Maxilaku', 3, 20, 2),
 (57, 'Ravioli Angelo', 5, 19.5, 2),
 (44, 'Gula Malacca', 2, 19.45, 3),
 (2, 'Chang', 1, 19, 3),
 (36, 'Inlagd Sill', 8, 19, 3),
 (40, 'Boston Crab Meat', 8, 18.4, 3),
 (1, 'Chai', 1, 18, 3),
 (35, 'Steeleye Stout', 1, 18, 3),
 (39, 'Chartreuse verte', 1, 18, 3),
 (76, 'Lakkalikööri', 1, 18, 3),
 (16, 'Pavlova', 3, 17.45, 3),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 3),
 (50, 'Valkoinen suklaa', 3, 16.25, 3),
 (15, 'Genen Shouyu', 2, 15.5, 3),
 (70, 'Outback Lager', 1, 15, 3),
 (73, 'Röd Kaviar', 8, 15, 3),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 3),
 (34, 'Sasquatch Ale', 1, 14, 3),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 3),
 (67, 'Laughing Lumberjack Lager', 1, 14, 3),
 (58, 'Escargots de Bourgogne', 8, 13.25, 3),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 4),
 (48, 'Chocolade', 3, 12.75, 4),
 (31, 'Gorgonzola Telino', 4, 12.5, 4),
 (68, 'Scottish Longbreads', 3, 12.5, 4),
 (46, 'Spegesild', 8, 12, 4),
 (3, 'Aniseed Syrup', 2, 10, 4),
 (21, "Sir Rodney's Scones", 3, 10, 4),
 (74, 'Longlife Tofu', 7, 10, 4),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 4),
 (45, 'Rogede sild', 8, 9.5, 4),
 (47, 'Zaanse koeken', 3, 9.5, 4),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 4),
 (23, 'Tunnbröd', 5, 9, 4),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 4),
 (54, 'Tourtière', 6, 7.45, 4),
 (52, 'Filo Mix', 5, 7, 4),
 (13, 'Konbu', 8, 6, 4),
 (24, 'Guaraná Fantástica', 1, 4.5, 4),
 (33, 'Geitost', 4, 2.5, 4)]

In [9]:
%%sql

-- 👉 Splits products into 3 price-based groups within each category


SELECT ProductID, ProductName, CategoryID, Price,
       NTILE(3) OVER (PARTITION BY CategoryID ORDER BY Price DESC) AS PriceGroup
FROM Products;

 * sqlite:///northwind1.db
Done.

[(38, 'Côte de Blaye', 1, 263.5, 1),
 (43, 'Ipoh Coffee', 1, 46, 1),
 (2, 'Chang', 1, 19, 1),
 (1, 'Chai', 1, 18, 1),
 (35, 'Steeleye Stout', 1, 18, 2),
 (39, 'Chartreuse verte', 1, 18, 2),
 (76, 'Lakkalikööri', 1, 18, 2),
 (70, 'Outback Lager', 1, 15, 2),
 (34, 'Sasquatch Ale', 1, 14, 3),
 (67, 'Laughing Lumberjack Lager', 1, 14, 3),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 3),
 (24, 'Guaraná Fantástica', 1, 4.5, 3),
 (63, 'Vegie-spread', 2, 43.9, 1),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 1),
 (61, "Sirop d'érable", 2, 28.5, 1),
 (6, "Grandma's Boysenberry Spread", 2, 25, 1),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 2),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 2),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 2),
 (44, 'Gula Malacca', 2, 19.45, 2),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 3),
 (15, 'Genen Shouyu', 2, 15.5, 3),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 3),
 (3, 'Aniseed Syrup', 2, 10, 3),
 (20, "Sir Rodney's Marmalade", 3, 81, 1),
 (62, 'Tarte au sucre', 3, 49.3, 1),
 (27, 'Schoggi Schokolade', 3, 43.9, 1),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 1),
 (49, 'Maxilaku', 3, 20, 1),
 (16, 'Pavlova', 3, 17.45, 2),
 (50, 'Valkoinen suklaa', 3, 16.25, 2),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 2),
 (48, 'Chocolade', 3, 12.75, 2),
 (68, 'Scottish Longbreads', 3, 12.5, 3),
 (21, "Sir Rodney's Scones", 3, 10, 3),
 (47, 'Zaanse koeken', 3, 9.5, 3),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 3),
 (59, 'Raclette Courdavault', 4, 55, 1),
 (12, 'Queso Manchego La Pastora', 4, 38, 1),
 (69, 'Gudbrandsdalsost', 4, 36, 1),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 1),
 (60, 'Camembert Pierrot', 4, 34, 2),
 (32, 'Mascarpone Fabioli', 4, 32, 2),
 (71, 'Flotemysost', 4, 21.5, 2),
 (11, 'Queso Cabrales', 4, 21, 3),
 (31, 'Gorgonzola Telino', 4, 12.5, 3),
 (33, 'Geitost', 4, 2.5, 3),
 (56, 'Gnocchi di nonna Alice', 5, 38, 1),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 1),
 (22, "Gustaf's Knäckebröd", 5, 21, 1),
 (57, 'Ravioli Angelo', 5, 19.5, 2),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 2),
 (23, 'Tunnbröd', 5, 9, 3),
 (52, 'Filo Mix', 5, 7, 3),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 1),
 (9, 'Mishi Kobe Niku', 6, 97, 1),
 (17, 'Alice Mutton', 6, 39, 2),
 (53, 'Perth Pasties', 6, 32.8, 2),
 (55, 'Pâté chinois', 6, 24, 3),
 (54, 'Tourtière', 6, 7.45, 3),
 (51, 'Manjimup Dried Apples', 7, 53, 1),
 (28, 'Rössle Sauerkraut', 7, 45.6, 1),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 2),
 (14, 'Tofu', 7, 23.25, 2),
 (74, 'Longlife Tofu', 7, 10, 3),
 (18, 'Carnarvon Tigers', 8, 62.5, 1),
 (10, 'Ikura', 8, 31, 1),
 (37, 'Gravad lax', 8, 26, 1),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 1),
 (36, 'Inlagd Sill', 8, 19, 2),
 (40, 'Boston Crab Meat', 8, 18.4, 2),
 (73, 'Röd Kaviar', 8, 15, 2),
 (58, 'Escargots de Bourgogne', 8, 13.25, 2),
 (46, 'Spegesild', 8, 12, 3),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 3),
 (45, 'Rogede sild', 8, 9.5, 3),
 (13, 'Konbu', 8, 6, 3)]

In [10]:
%%sql

-- 👉 Divides All products into 10 groups based on price ordering.


SELECT ProductID, ProductName, CategoryID, Price,

    ROW_NUMBER() OVER (ORDER BY Price DESC) AS RowNum,
    
    RANK() OVER (ORDER BY Price DESC) AS RANK,
    
    DENSE_RANK() OVER (ORDER BY Price DESC) AS DENSE_RANK,
    NTILE(10) OVER (ORDER BY Price DESC) AS PriceGroup
FROM Products;

 * sqlite:///northwind1.db
Done.

[(38, 'Côte de Blaye', 1, 263.5, 1, 1, 1, 1),
 (29, 'Thüringer Rostbratwurst', 6, 123.79, 2, 2, 2, 1),
 (9, 'Mishi Kobe Niku', 6, 97, 3, 3, 3, 1),
 (20, "Sir Rodney's Marmalade", 3, 81, 4, 4, 4, 1),
 (18, 'Carnarvon Tigers', 8, 62.5, 5, 5, 5, 1),
 (59, 'Raclette Courdavault', 4, 55, 6, 6, 6, 1),
 (51, 'Manjimup Dried Apples', 7, 53, 7, 7, 7, 1),
 (62, 'Tarte au sucre', 3, 49.3, 8, 8, 8, 1),
 (43, 'Ipoh Coffee', 1, 46, 9, 9, 9, 2),
 (28, 'Rössle Sauerkraut', 7, 45.6, 10, 10, 10, 2),
 (27, 'Schoggi Schokolade', 3, 43.9, 11, 11, 11, 2),
 (63, 'Vegie-spread', 2, 43.9, 12, 11, 11, 2),
 (8, 'Northwoods Cranberry Sauce', 2, 40, 13, 13, 12, 2),
 (17, 'Alice Mutton', 6, 39, 14, 14, 13, 2),
 (12, 'Queso Manchego La Pastora', 4, 38, 15, 15, 14, 2),
 (56, 'Gnocchi di nonna Alice', 5, 38, 16, 15, 14, 2),
 (69, 'Gudbrandsdalsost', 4, 36, 17, 17, 15, 3),
 (72, 'Mozzarella di Giovanni', 4, 34.8, 18, 18, 16, 3),
 (60, 'Camembert Pierrot', 4, 34, 19, 19, 17, 3),
 (64, 'Wimmers gute Semmelknödel', 5, 33.25, 20, 20, 18, 3),
 (53, 'Perth Pasties', 6, 32.8, 21, 21, 19, 3),
 (32, 'Mascarpone Fabioli', 4, 32, 22, 22, 20, 3),
 (26, 'Gumbär Gummibärchen', 3, 31.23, 23, 23, 21, 3),
 (10, 'Ikura', 8, 31, 24, 24, 22, 3),
 (7, "Uncle Bob's Organic Dried Pears", 7, 30, 25, 25, 23, 4),
 (61, "Sirop d'érable", 2, 28.5, 26, 26, 24, 4),
 (37, 'Gravad lax', 8, 26, 27, 27, 25, 4),
 (30, 'Nord-Ost Matjeshering', 8, 25.89, 28, 28, 26, 4),
 (6, "Grandma's Boysenberry Spread", 2, 25, 29, 29, 27, 4),
 (55, 'Pâté chinois', 6, 24, 30, 30, 28, 4),
 (14, 'Tofu', 7, 23.25, 31, 31, 29, 4),
 (4, "Chef Anton's Cajun Seasoning", 2, 22, 32, 32, 30, 4),
 (71, 'Flotemysost', 4, 21.5, 33, 33, 31, 5),
 (5, "Chef Anton's Gumbo Mix", 2, 21.35, 34, 34, 32, 5),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 21.05, 35, 35, 33, 5),
 (11, 'Queso Cabrales', 4, 21, 36, 36, 34, 5),
 (22, "Gustaf's Knäckebröd", 5, 21, 37, 36, 34, 5),
 (49, 'Maxilaku', 3, 20, 38, 38, 35, 5),
 (57, 'Ravioli Angelo', 5, 19.5, 39, 39, 36, 5),
 (44, 'Gula Malacca', 2, 19.45, 40, 40, 37, 5),
 (2, 'Chang', 1, 19, 41, 41, 38, 6),
 (36, 'Inlagd Sill', 8, 19, 42, 41, 38, 6),
 (40, 'Boston Crab Meat', 8, 18.4, 43, 43, 39, 6),
 (1, 'Chai', 1, 18, 44, 44, 40, 6),
 (35, 'Steeleye Stout', 1, 18, 45, 44, 40, 6),
 (39, 'Chartreuse verte', 1, 18, 46, 44, 40, 6),
 (76, 'Lakkalikööri', 1, 18, 47, 44, 40, 6),
 (16, 'Pavlova', 3, 17.45, 48, 48, 41, 6),
 (66, 'Louisiana Hot Spiced Okra', 2, 17, 49, 49, 42, 7),
 (50, 'Valkoinen suklaa', 3, 16.25, 50, 50, 43, 7),
 (15, 'Genen Shouyu', 2, 15.5, 51, 51, 44, 7),
 (70, 'Outback Lager', 1, 15, 52, 52, 45, 7),
 (73, 'Röd Kaviar', 8, 15, 53, 52, 45, 7),
 (25, 'NuNuCa Nuß-Nougat-Creme', 3, 14, 54, 54, 46, 7),
 (34, 'Sasquatch Ale', 1, 14, 55, 54, 46, 7),
 (42, 'Singaporean Hokkien Fried Mee', 5, 14, 56, 54, 46, 7),
 (67, 'Laughing Lumberjack Lager', 1, 14, 57, 54, 46, 8),
 (58, 'Escargots de Bourgogne', 8, 13.25, 58, 58, 47, 8),
 (77, 'Original Frankfurter grüne Soße', 2, 13, 59, 59, 48, 8),
 (48, 'Chocolade', 3, 12.75, 60, 60, 49, 8),
 (31, 'Gorgonzola Telino', 4, 12.5, 61, 61, 50, 8),
 (68, 'Scottish Longbreads', 3, 12.5, 62, 61, 50, 8),
 (46, 'Spegesild', 8, 12, 63, 63, 51, 8),
 (3, 'Aniseed Syrup', 2, 10, 64, 64, 52, 9),
 (21, "Sir Rodney's Scones", 3, 10, 65, 64, 52, 9),
 (74, 'Longlife Tofu', 7, 10, 66, 64, 52, 9),
 (41, "Jack's New England Clam Chowder", 8, 9.65, 67, 67, 53, 9),
 (45, 'Rogede sild', 8, 9.5, 68, 68, 54, 9),
 (47, 'Zaanse koeken', 3, 9.5, 69, 68, 54, 9),
 (19, 'Teatime Chocolate Biscuits', 3, 9.2, 70, 70, 55, 9),
 (23, 'Tunnbröd', 5, 9, 71, 71, 56, 10),
 (75, 'Rhönbräu Klosterbier', 1, 7.75, 72, 72, 57, 10),
 (54, 'Tourtière', 6, 7.45, 73, 73, 58, 10),
 (52, 'Filo Mix', 5, 7, 74, 74, 59, 10),
 (13, 'Konbu', 8, 6, 75, 75, 60, 10),
 (24, 'Guaraná Fantástica', 1, 4.5, 76, 76, 61, 10),
 (33, 'Geitost', 4, 2.5, 77, 77, 62, 10)]

# The notebook ends here....!

# 5️⃣ 2nd cheapest product overall

In [ ]:
%%sql

-- 👉 Adds a column that always shows the second cheapest product overall.


SELECT 
    CategoryID,
    ProductID,
    ProductName,
    Price,
    NTH_VALUE(ProductName, 2) OVER (
        Partition by CategoryID
        ORDER BY Price 
        ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS second_cheapest_product
FROM Products;

# 6️⃣ MIN() and MAX() — Price Range per Category

In [ ]:
%%sql

-- 👉 Finds the second most expensive product within each CategoryID.

SELECT 
    CategoryID,
    ProductName,
    Price,
    NTH_VALUE(ProductName, 2) OVER (
        PARTITION BY CategoryID
        ORDER BY Price DESC
        ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS second_costliest_in_category
FROM Products;

# 7️⃣ 🏆 Advanced Example – Combining all three

#### Let’s compare the cheapest, most expensive, and 2nd cheapest product per supplier.

In [ ]:
%%sql

-- 👉 This gives a full summary per supplier using FIRST_VALUE, LAST_VALUE, and NTH_VALUE together.


SELECT 
    SupplierID,
    ProductName,
    Price,
    
    FIRST_VALUE(ProductName) OVER (
        PARTITION BY SupplierID ORDER BY Price
    ) AS cheapest_product,
    
    
    LAST_VALUE(ProductName) OVER (
        PARTITION BY SupplierID ORDER BY Price
        ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS costliest_product,
    
    
    NTH_VALUE(ProductName, 2) OVER (
        PARTITION BY SupplierID ORDER BY Price
        ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS second_cheapest_product
    
FROM Products;

# Notebook Ends Here.

# 8️⃣ Combining Multiple Window Aggregates

In [ ]:
%%sql
SELECT 
    ProductID,
    ProductName,
    CategoryID,
    Price,
    SUM(Price) OVER () AS total_price_all_products,
    COUNT(*) OVER (PARTITION BY CategoryID) AS product_count,
    SUM(Price) OVER (PARTITION BY CategoryID) AS total_price,
    AVG(Price) OVER (PARTITION BY CategoryID) AS avg_price,
    MIN(Price) OVER (PARTITION BY CategoryID) AS min_price,
    MAX(Price) OVER (PARTITION BY CategoryID) AS max_price
FROM Products;

In [ ]:
%%sql
SELECT 
    CategoryID,
    COUNT(*) AS product_count,
    SUM(Price) AS total_price,
    AVG(Price) AS avg_price,
    MIN(Price) AS min_price,
    MAX(Price) AS max_price
FROM Products
GROUP BY CategoryID;

# 9️⃣ COUNT() with Running Count (ROW-Like Behavior)

In [ ]:
%%sql
SELECT 
    ProductID,
    ProductName,
    CategoryID,
    Price,
    COUNT(*) OVER (
        PARTITION BY CategoryID
        ORDER BY ProductID
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS running_product_count
FROM Products;

GROUP BY Equivalent

❌ Like cumulative sums, running counts cannot be done with plain GROUP BY.
We can use correlated subquery:

In [ ]:
%%sql
SELECT 
    p1.ProductID,
    p1.ProductName,
    p1.CategoryID,
    p1.Price,
    (
        SELECT COUNT(*)
        FROM Products p2
        WHERE p2.CategoryID = p1.CategoryID
          AND p2.ProductID <= p1.ProductID
    ) AS running_product_count
FROM Products p1
ORDER BY p1.CategoryID, p1.ProductID;

In [ ]:
%%sql

-- 👉 Gives each product a unique sequential number within its category

SELECT ProductID, ProductName, CategoryID, Price,
       ROW_NUMBER() OVER (ORDER BY Price DESC) AS RowNum
FROM Products;

# Count the number of customers per country

In [ ]:
%%sql

SELECT 

Country, 

COUNT(*) AS Total_Customers

FROM Customers

GROUP BY Country;

In [ ]:
%%sql

SELECT 

COUNT(*) AS Total_Customers

FROM Customers;

In [ ]:
%%sql

SELECT 
Country, 
COUNT(*) AS Total_Customers
FROM Customers
GROUP BY Country
ORDER BY Total_Customers
desc;

# Get the average price of the product in each category

In [ ]:
%%sql

SELECT *
FROM Products
Limit 5;

In [ ]:
%%sql

SELECT AVG(Price) AS AvgPrice 
FROM Products;

In [ ]:
%%sql

SELECT AVG(Price) AS AvgPrice 
FROM Products
group by CategoryID;

In [ ]:
%%sql

SELECT CategoryID, AVG(Price) AS AvgPrice 
FROM Products
group by CategoryID;

In [ ]:
%%sql

select * FROM categories;

In [ ]:
%%sql

SELECT CategoryID, AVG(Price) AS AvgPrice 
FROM Products
group by CategoryID
order by AVG(Price);

In [ ]:
%%sql

SELECT CategoryID, AVG(Price) AS AvgPrice 
FROM Products
group by CategoryID
order by AVG(Price);

## repeate same for sum of price within each category

# Get Minimum and Maxmium Price per Category

In [ ]:
%%sql

SELECT CategoryID, 
MAX(Price) AS Max_Price, 
MIN(Price) AS Min_Price

FROM Products
GROUP BY CategoryID;

In [ ]:
%%sql

select * FROM categories;

In [ ]:
%%sql

SELECT 
    c.CategoryName,
    p.CategoryID, 
    MAX(p.Price) AS Max_Price, 
    MIN(p.Price) AS Min_Price
FROM Products p
JOIN Categories c 
    ON p.CategoryID = c.CategoryID
GROUP BY 
    c.CategoryName, 
    p.CategoryID;

In [ ]:
%%sql

SELECT country,
city,
count(*) AS Total_customers_per_country_per_city
From Customers

group by country, city;

In [ ]:
%%sql

SELECT country, city, count(*) AS total_cust

From Customers

group by country, city

having count(*) > 2

order by count(*) asc;

# 🚨 Common Mistakes
## ❌ Using columns in SELECT that are not in GROUP BY or aggregate functions.

## ❌ Using WHERE instead of HAVING for aggregated values.

# ✅ Best Practices

### Always use aggregate functions with columns not in the GROUP BY clause.

### Use HAVING to filter aggregated results.

### Use aliases to improve readability of output.

In [ ]:
%%sql

SELECT * 
FROM Suppliers
Limit 5;

# Get all suppliers and customers from London. (Using Multiple CTEs)

In [ ]:
%%sql

WITH LondonCustomers AS (
    SELECT CustomerID, ContactName, City FROM Customers WHERE City = 'London'
),
LondonSuppliers AS (
    SELECT SupplierID, ContactName, City FROM  WHERE City =Suppliers 'London'
)
SELECT * FROM LondonCustomers
UNION ALL
SELECT * FROM LondonSuppliers;

In [ ]:
%%sql

WITH LondonCustomers AS (
    SELECT 
        CustomerID AS ID, 
        ContactName, 
        City, 
        'Customer' AS Type
    FROM Customers 
    WHERE City = 'London'
),
LondonSuppliers AS (
    SELECT 
        SupplierID AS ID, 
        ContactName, 
        City, 
        'Supplier' AS Type
    FROM Suppliers 
    WHERE City = 'London'
)
SELECT * FROM LondonCustomers
UNION ALL
SELECT * FROM LondonSuppliers;

In [ ]:
%%sql

SELECT * FROM Products
Limit 10;

In [ ]:
%%sql

WITH AvgPriceCTE AS (
    SELECT AVG(Price) AS AvgPrice FROM Products
)
SELECT *
FROM Products
WHERE Price > (SELECT AvgPrice FROM AvgPriceCTE);

# 📌 This gives you the number of products in each category.

In [ ]:
%%sql

WITH CategoryCounts AS (
    SELECT CategoryID, COUNT(*) AS TotalProducts
    FROM Products
    GROUP BY CategoryID
)
SELECT *
FROM CategoryCounts;

# CTE to Identify Duplicate Prices
📌 Finds all products that share the same price as others (duplicates).

In [ ]:
%%sql

WITH PriceCounts AS (
    SELECT Price, COUNT(*) AS Occurrences
    FROM Products
    GROUP BY Price
    HAVING COUNT(*) > 1
)
SELECT *
FROM Products
WHERE Price IN (SELECT Price FROM PriceCounts) order by price;

# CTE to Get the Cheapest Product Per Category

In [ ]:
%%sql

SELECT CategoryID, MIN(Price) AS MinPrice
    FROM Products
    GROUP BY CategoryID;

In [ ]:
%%sql

WITH MinPrices AS (
    SELECT CategoryID, MIN(Price) AS MinPrice
    FROM Products
    GROUP BY CategoryID
)
SELECT *
FROM Products
WHERE (CategoryID, Price) IN (
    SELECT CategoryID, MinPrice FROM MinPrices
) order by CategoryID;

# Get the employees who handle more than 2 territories.

In [ ]:
%%sql

WITH TerritoryCount AS (
    SELECT EmployeeID, COUNT(*) AS TotalTerritories
    FROM EmployeeTerritories
    GROUP BY EmployeeID
)
SELECT E.FirstName, E.LastName, T.TotalTerritories
FROM Employees E
JOIN TerritoryCount T ON E.EmployeeID = T.EmployeeID
WHERE T.TotalTerritories > 2;

# 📌 Returns the most expensive product in each category.

In [ ]:
%%sql

WITH RankedCategory AS (
    SELECT ProductID, ProductName, CategoryID, Price,
           RANK() OVER (PARTITION BY CategoryID ORDER BY Price DESC) AS RankInCategory
    FROM Products
)
SELECT *
FROM RankedCategory
WHERE RankInCategory = 1;

# 📌 Filters category 3 products, then returns the top 3 most expensive among them.

In [ ]:
%%sql

WITH Filtered AS (
    SELECT * FROM Products WHERE CategoryID = 3
),
Ranked AS (
    SELECT ProductID, ProductName, Price,
           DENSE_RANK() OVER (ORDER BY Price DESC) AS PriceRank
    FROM Filtered
)
SELECT * FROM Ranked WHERE PriceRank <= 3;

In [ ]:
%%sql

SELECT * FROM Products
ORDER BY ProductName;

# 📌 Categorizes products into 'Low', 'Medium', and 'High' price brackets.

In [ ]:
%%sql

WITH PriceBuckets AS (
    SELECT ProductID, ProductName, Price,
           CASE 
               WHEN Price < 10 THEN 'Low'
               WHEN Price BETWEEN 10 AND 30 THEN 'Medium'
               ELSE 'High'
           END AS PriceCategory
    FROM Products
)
SELECT *
FROM PriceBuckets
WHERE PriceCategory = 'Low';

# Recursive CTEs

In [ ]:
%%sql

WITH RECURSIVE FactorialCTE(n, fact) AS (
    SELECT 1, 1
    UNION ALL
    SELECT n + 1, (n + 1) * fact
    FROM FactorialCTE
    WHERE n < 5
)
SELECT * FROM FactorialCTE;

# Return all customers that starts with "E" and are at least 3 characters in length

In [ ]:
%%sql

SELECT * FROM Customers
WHERE CustomerName LIKE 'E__%';

# END..... Practice Below...

In [ ]:
%%sql

SELECT * 
FROM Customers
WHERE country = 'Brazil';

In [ ]:
%%sql

SELECT * 
FROM Customers
WHERE CustomerID=3;

In [ ]:
%%sql

SELECT * FROM Products;

In [ ]:
%%sql

SELECT *
FROM Products
WHERE Price > 40;

In [ ]:
%%sql

SELECT * 
FROM Products
WHERE Price < 40;

In [ ]:
%%sql

SELECT * 
FROM Products
WHERE Price >= 30;

In [ ]:
%%sql

SELECT * 
FROM Products
WHERE Price <= 30;

In [ ]:
%%sql

SELECT * FROM Products
WHERE Price <> 30;

In [ ]:
%%sql

SELECT * 
FROM Products
WHERE Price BETWEEN 30 AND 40;

In [ ]:
%%sql

SELECT * 
FROM Customers
WHERE City IN ('Paris','London');

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql

In [ ]:
%%sql